import {buildMcpInputContinuationPreview,fingerprintMcpInputContinuationPreview,executeModernMcpToolContinuation} from '../src/mcp-adapter.js';

const byId=id=>document.getElementById(id);
const status=byId('status'),result=byId('result'),runtimeList=byId('runtime'),diagnosis=byId('diagnosis'),blockers=byId('blockers'),button=byId('inspect'),intent=byId('intent');
const apiButton=byId('compile-api-tools'),apiResult=byId('api-tools-result'),apiSummary=byId('api-tools-summary'),apiOperation=byId('api-operation'),apiArguments=byId('api-arguments'),apiPreviewButton=byId('preview-api-request'),apiPreviewResult=byId('api-preview-result'),apiApprovalLabel=byId('api-approval-label'),apiApproval=byId('api-execution-approval'),apiExecuteButton=byId('execute-api-request'),apiExecutionResult=byId('api-execution-result');
const mcpButton=byId('inspect-mcp'),mcpEndpoint=byId('mcp-endpoint'),mcpResult=byId('mcp-result'),mcpSummary=byId('mcp-summary'),mcpTools=byId('mcp-tools'),mcpListButton=byId('list-mcp-tools'),mcpToolsSummary=byId('mcp-tools-summary'),mcpTool=byId('mcp-tool'),mcpArguments=byId('mcp-arguments'),mcpPreviewButton=byId('preview-mcp-tool'),mcpPreview=byId('mcp-preview'),mcpApprovalLabel=byId('mcp-approval-label'),mcpApproval=byId('mcp-execution-approval'),mcpExecuteButton=byId('execute-mcp-tool'),mcpExecution=byId('mcp-execution');
const mcpContinuation=byId('mcp-continuation'),mcpInputRequests=byId('mcp-input-requests'),mcpInputResponses=byId('mcp-input-responses'),mcpContinuationPreviewButton=byId('preview-mcp-continuation'),mcpContinuationPreview=byId('mcp-continuation-preview'),mcpContinuationApprovalLabel=byId('mcp-continuation-approval-label'),mcpContinuationApproval=byId('mcp-continuation-approval'),mcpContinuationExecuteButton=byId('execute-mcp-continuation');
let compiledApiTools=[],currentPreview=null,mcpCandidates=[],currentMcpPreview=null,mcpInteraction=null,currentMcpContinuation=null;

function clear(node){while(node.firstChild)node.removeChild(node.firstChild);}
function addPair(term,value){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=term;dd.textContent=value??'Unknown';runtimeList.append(dt,dd);}
function render(data){clear(runtimeList);clear(diagnosis);clear(blockers);const r=data.runtime??{};addPair('Page',r.url??'Unavailable');addPair('Secure context',String(Boolean(r.secureContext)));addPair('Frameworks',(r.frameworkHints??[]).map(x=>x.name).join(', ')||'No framework marker established');addPair('Open shadow roots',String(r.dom?.openShadowRoots??0));addPair('Iframes',String(r.dom?.iframes??0));if(data.ok){const d=data.diagnosis??{};const strong=document.createElement('strong'),p=document.createElement('p');strong.textContent=`${d.status??'unknown'} · ${d.primaryPath??'unknown'}`;p.textContent=d.recommendedAction??'No recommendation returned.';diagnosis.append(strong,p);for(const item of d.blockers??[]){const li=document.createElement('li'),title=document.createElement('strong'),reason=document.createElement('p'),remediation=document.createElement('p');title.textContent=item.code??'Restriction';reason.textContent=item.reason??'';remediation.textContent=item.remediation??'';li.append(title,reason,remediation);blockers.append(li);}if(!(d.blockers??[]).length){const li=document.createElement('li');li.textContent='No blocking condition was established from the observed evidence.';blockers.append(li);}status.textContent='Inspection complete.';}else{const p=document.createElement('p');p.textContent=data.error??'Inspection failed.';diagnosis.append(p);status.textContent='Local inspection completed, but KATA diagnosis was unavailable.';}result.hidden=false;}
function consumeApiPreview(){currentPreview=null;clear(apiPreviewResult);apiPreviewResult.hidden=true;apiApproval.checked=false;apiApprovalLabel.hidden=true;apiExecuteButton.disabled=true;}
function invalidateApiPreview(){consumeApiPreview();clear(apiExecutionResult);apiExecutionResult.hidden=true;}
function parseObject(text,label){let value;try{value=JSON.parse(text||'{}');}catch{throw new Error(`${label} must be valid JSON.`);}if(!value||typeof value!=='object'||Array.isArray(value))throw new Error(`${label} must be a JSON object.`);return value;}
function parseApiArguments(){return parseObject(apiArguments.value,'API arguments');}
function populateApiOperations(tools){clear(apiOperation);for(const tool of tools){const option=document.createElement('option');option.value=tool.name;option.textContent=`${tool.name} — ${tool.execution?.method??'?'}`;apiOperation.append(option);}apiPreviewButton.disabled=tools.length===0;}
function renderApiTools(data){clear(apiSummary);invalidateApiPreview();compiledApiTools=[];if(!data?.ok){const p=document.createElement('p');p.textContent=data?.error??'API tool compilation failed.';apiSummary.append(p);apiResult.hidden=false;populateApiOperations([]);return;}const compilation=data.compilation??{},tools=compilation.tools??[],rejected=compilation.rejected??[];compiledApiTools=tools;const headline=document.createElement('strong'),note=document.createElement('p'),list=document.createElement('ul');headline.textContent=`${tools.length} tool contract${tools.length===1?'':'s'} compiled locally`;note.textContent=`${rejected.length} operation${rejected.length===1?' was':'s were'} rejected because KATA could not establish a safe, complete agent contract. Compilation itself executes nothing.`;for(const tool of tools.slice(0,25)){const li=document.createElement('li'),name=document.createElement('strong'),meta=document.createElement('span');name.textContent=tool.name;meta.textContent=` — ${tool.execution?.method??'?'} · ${tool.execution?.requiresAuthorization?'declared authorization':'no declared authorization'}${(tool.execution?.streamingMedia??[]).length?` · stream ${(tool.execution.streamingMedia??[]).join(', ')}`:''}`;li.append(name,meta);list.append(li);}apiSummary.append(headline,note,list);populateApiOperations(tools);apiResult.hidden=false;}
function renderApiPreview(data){invalidateApiPreview();if(!data?.ok){const p=document.createElement('p');p.textContent=data?.error??'API request preview failed.';apiPreviewResult.append(p);apiPreviewResult.hidden=false;return;}currentPreview=data;const p=data.preview??{},title=document.createElement('strong'),pre=document.createElement('pre'),note=document.createElement('p');title.textContent=`${p.method??'?'} · ${p.readyToExecute?'eligible for explicit execution':'not executable'}`;pre.textContent=JSON.stringify({url:p.url,credentialMode:p.credentialMode,stateChanging:p.stateChanging,redirect:p.redirect,timeoutMs:p.timeoutMs,maxResponseBytes:p.maxResponseBytes,headers:p.headers,body:p.body,previewFingerprint:data.previewFingerprint,blockedReason:p.blockedReason},null,2);note.textContent=p.requiresAuthorization?'The site declares authorization. KATA will use only browser-managed same-origin credentials; it will not read or expose them.':'No authorization is declared. KATA will omit ambient browser credentials.';apiPreviewResult.append(title,note,pre);apiPreviewResult.hidden=false;apiApprovalLabel.hidden=!p.stateChanging;apiExecuteButton.disabled=!p.readyToExecute||(p.stateChanging&&!apiApproval.checked);}
function renderApiExecution(data){clear(apiExecutionResult);const title=document.createElement('strong'),pre=document.createElement('pre');if(data?.receipt){const receipt=data.receipt,response=data.response??{};title.textContent=`${receipt.outcome??'unknown'} · HTTP ${receipt.status??'no response'}`;pre.textContent=JSON.stringify({error:data.error??null,receipt,response:{ok:response.ok,status:response.status,statusText:response.statusText,url:response.url,contentType:response.contentType,bytes:response.bytes,truncated:response.truncated,outcome:response.outcome,networkError:response.networkError,bodyText:response.bodyText}},null,2);}else{title.textContent='Execution did not start';pre.textContent=data?.error??'API execution failed before a target request was attempted.';}apiExecutionResult.append(title,pre);apiExecutionResult.hidden=false;}

function clearMcpPreview(){currentMcpPreview=null;clear(mcpPreview);mcpPreview.hidden=true;mcpApproval.checked=false;mcpApprovalLabel.hidden=true;mcpExecuteButton.disabled=true;}
function clearMcpContinuationPreview(){currentMcpContinuation=null;clear(mcpContinuationPreview);mcpContinuationPreview.hidden=true;mcpContinuationApproval.checked=false;mcpContinuationApprovalLabel.hidden=true;mcpContinuationExecuteButton.disabled=true;}
function clearMcpContinuation(){mcpInteraction=null;clearMcpContinuationPreview();clear(mcpInputRequests);mcpInputResponses.value='{}';mcpContinuation.hidden=true;}
function invalidateMcpPreview(){clearMcpPreview();clearMcpContinuation();clear(mcpExecution);mcpExecution.hidden=true;}
function populateMcpTools(tools){clear(mcpTool);for(const tool of tools){const option=document.createElement('option');option.value=tool.name;option.textContent=tool.title?`${tool.name} — ${tool.title}`:tool.name;mcpTool.append(option);}mcpPreviewButton.disabled=tools.length===0;}
function renderMcp(data){clear(mcpSummary);invalidateMcpPreview();mcpCandidates=[];const strong=document.createElement('strong'),p=document.createElement('p'),recommendation=document.createElement('p'),pre=document.createElement('pre');const e=data.environment??{};strong.textContent=`${e.mcpEndpoint??'unknown'} · ${e.mcpModernProtocol??'unknown'} · auth ${e.mcpAuth??'unknown'}`;p.textContent=data.ok?'MCP discovery evidence collected locally. No tool was invoked and no authorization flow was started.':(data.error??'MCP inspection failed.');const d=data.diagnosis;if(d)recommendation.textContent=`KATA: ${d.status??'unknown'} · ${d.primaryPath??'unknown'} — ${d.recommendedAction??''}`;else if(data.diagnosisError)recommendation.textContent=`KATA diagnosis unavailable: ${data.diagnosisError}`;const local={endpoint:data.endpoint??null,server:data.server??null,authorization:data.authorization??null,environment:e};pre.textContent=JSON.stringify(local,null,2);mcpSummary.append(strong,p,recommendation,pre);mcpResult.hidden=false;mcpTools.hidden=!(data.ok&&e.mcpModernProtocol==='supported'&&e.mcpAuth==='none'&&data.server?.capabilities?.tools!==undefined);}
function renderMcpTools(data){clear(mcpToolsSummary);invalidateMcpPreview();mcpCandidates=[];if(!data?.ok){const p=document.createElement('p');p.textContent=data?.error??'MCP tools/list failed.';mcpToolsSummary.append(p);populateMcpTools([]);return;}const inventory=data.inventory??{},tools=inventory.tools??[],rejected=inventory.rejected??[];mcpCandidates=tools;const title=document.createElement('strong'),note=document.createElement('p'),list=document.createElement('ul');title.textContent=`${tools.length} executable public MCP tool contract${tools.length===1?'':'s'} discovered`;note.textContent=`${rejected.length} tool definition${rejected.length===1?' was':'s were'} rejected because KATA could not safely execute its transport/schema contract. Tool annotations are displayed only as untrusted metadata; every call still requires explicit approval.`;for(const tool of tools.slice(0,50)){const li=document.createElement('li');li.textContent=tool.title?`${tool.name} — ${tool.title}`:tool.name;list.append(li);}mcpToolsSummary.append(title,note,list);populateMcpTools(tools);}
function renderMcpPreview(data){invalidateMcpPreview();if(!data?.ok){const p=document.createElement('p');p.textContent=data?.error??'MCP tool preview failed.';mcpPreview.append(p);mcpPreview.hidden=false;return;}currentMcpPreview=data;const title=document.createElement('strong'),note=document.createElement('p'),pre=document.createElement('pre');title.textContent=`${data.preview?.toolName??'tool'} · exact public MCP call preview`;note.textContent='No cookie, bearer token, API key, or browser credential will be sent. KATA re-discovers tools/list before execution; any contract change invalidates this fingerprint.';pre.textContent=JSON.stringify({endpoint:data.preview?.endpoint,toolName:data.preview?.toolName,arguments:data.preview?.arguments,mirroredHeaders:Object.fromEntries(Object.entries(data.preview?.headers??{}).filter(([name])=>name.startsWith('Mcp-Param-'))),credentials:data.preview?.credentials,redirect:data.preview?.redirect,automaticRetries:data.preview?.automaticRetries,maxResponseBytes:data.preview?.maxResponseBytes,previewFingerprint:data.previewFingerprint},null,2);mcpPreview.append(title,note,pre);mcpPreview.hidden=false;mcpApprovalLabel.hidden=false;mcpExecuteButton.disabled=!mcpApproval.checked;}
function renderMcpExecution(data){clear(mcpExecution);const title=document.createElement('strong'),pre=document.createElement('pre');if(data?.receipt){title.textContent=`${data.receipt.resultType??'unknown'} · ${data.receipt.isError?'tool error':data.receipt.inputRequired?'input required':'tool completed'}`;pre.textContent=JSON.stringify({ok:data.ok,receipt:data.receipt,result:data.result,error:data.error??null},null,2);}else{title.textContent='MCP tool execution did not start';pre.textContent=data?.error??'MCP execution failed before a call was attempted.';}mcpExecution.append(title,pre);mcpExecution.hidden=false;}
function defaultInputResponses(requests){return Object.fromEntries(Object.keys(requests??{}).map(key=>[key,{action:'accept',content:{}}]));}
function beginMcpContinuation(originalPreview,originalFingerprint,data){clearMcpContinuation();const continuation=data?.continuation;if(!data?.result||data.result.resultType!=='input_required'||!continuation)return;mcpInteraction={originalPreview,originalFingerprint,inputRequiredResult:data.result,round:continuation.round,maxRounds:continuation.maxRounds};const title=document.createElement('strong');title.textContent=`Round ${continuation.round} of ${continuation.maxRounds}`;mcpInputRequests.append(title);for(const [key,request] of Object.entries(continuation.inputRequests??{})){const section=document.createElement('section'),heading=document.createElement('h4'),message=document.createElement('p'),pre=document.createElement('pre');heading.textContent=key;message.textContent=request?.params?.message??'MCP server requested user input.';pre.textContent=JSON.stringify({method:request?.method??null,mode:request?.params?.mode??null,requestedSchema:request?.params?.requestedSchema??null},null,2);section.append(heading,message,pre);mcpInputRequests.append(section);}if(!continuation.continuationSupported){const warning=document.createElement('p');warning.textContent=`KATA will not fabricate unsupported client behavior: ${(continuation.unsupported??[]).map(x=>x.reason).join('; ')||'unsupported input request'}.`;mcpInputRequests.append(warning);mcpContinuationPreviewButton.disabled=true;mcpInputResponses.value='{}';}else{mcpContinuationPreviewButton.disabled=false;mcpInputResponses.value=JSON.stringify(defaultInputResponses(continuation.inputRequests),null,2);}mcpContinuation.hidden=false;}
function renderMcpContinuationPreview(preview,fingerprint){clearMcpContinuationPreview();currentMcpContinuation={preview,fingerprint};const title=document.createElement('strong'),note=document.createElement('p'),pre=document.createElement('pre');title.textContent=`Round ${preview.round} · exact continuation preview`;note.textContent='Explicit approval is required for this round. KATA sends only the current round responses and echoes requestState exactly as received; it does not accumulate prior answers or retry automatically.';const requestStateBytes=preview.requestState==null?0:new TextEncoder().encode(preview.requestState).length;pre.textContent=JSON.stringify({toolName:preview.toolName,endpoint:preview.endpoint,round:preview.round,maxRounds:preview.maxRounds,inputRequestKeys:preview.inputRequestKeys,inputResponses:preview.inputResponses,requestStatePresent:preview.requestState!=null,requestStateBytes,credentials:preview.credentials,redirect:preview.redirect,automaticRetries:preview.automaticRetries,continuationFingerprint:fingerprint},null,2);mcpContinuationPreview.append(title,note,pre);mcpContinuationPreview.hidden=false;mcpContinuationApprovalLabel.hidden=false;mcpContinuationExecuteButton.disabled=!mcpContinuationApproval.checked;}
async function assertMcpContinuationContext(preview){const tabs=await chrome.tabs.query({active:true,currentWindow:true}),tab=tabs?.[0];if(!Number.isInteger(tab?.id))throw new Error('The active browser tab is no longer available.');let page,endpoint;try{page=new URL(String(tab.url??''));endpoint=new URL(String(preview?.endpoint??''));}catch{throw new Error('The MCP continuation no longer has a valid authorized HTTP(S) context.');}if(!['http:','https:'].includes(page.protocol)||page.origin!==endpoint.origin)throw new Error('The active tab changed origin. KATA will not continue an MCP call on a different site.');return true;}

button.addEventListener('click',async()=>{button.disabled=true;result.hidden=true;status.textContent='Inspecting the explicitly authorized active tab…';try{render(await chrome.runtime.sendMessage({type:'inspect-active-tab',intent:intent.value})??{ok:false,error:'No response from the KATA extension service worker.'});}catch(error){status.textContent=String(error?.message??error);result.hidden=true;}finally{button.disabled=false;}});
apiButton.addEventListener('click',async()=>{apiButton.disabled=true;apiResult.hidden=true;status.textContent='Discovering API descriptions and compiling local agent contracts…';try{const data=await chrome.runtime.sendMessage({type:'compile-api-tools',includeWellKnownCatalog:true,maxDescriptions:3,maxTools:50});renderApiTools(data??{ok:false,error:'No API compiler response.'});status.textContent='API agent contracts compiled locally. Select one to generate an exact execution preview.';}catch(error){status.textContent=String(error?.message??error);apiResult.hidden=true;}finally{apiButton.disabled=false;}});
apiOperation.addEventListener('change',invalidateApiPreview);apiArguments.addEventListener('input',invalidateApiPreview);apiApproval.addEventListener('change',()=>{apiExecuteButton.disabled=!currentPreview?.preview?.readyToExecute||(currentPreview?.preview?.stateChanging&&!apiApproval.checked);});
apiPreviewButton.addEventListener('click',async()=>{apiPreviewButton.disabled=true;invalidateApiPreview();status.textContent='Re-discovering the live API contract and binding an exact request preview…';try{const data=await chrome.runtime.sendMessage({type:'preview-api-tool',operationName:apiOperation.value,arguments:parseApiArguments(),includeWellKnownCatalog:true,maxDescriptions:3,maxTools:50});renderApiPreview(data??{ok:false,error:'No API preview response.'});status.textContent=data?.ok?'Fresh API request preview created. Review it before executing.':'API request preview failed.';}catch(error){renderApiPreview({ok:false,error:String(error?.message??error)});status.textContent='API request preview failed.';}finally{apiPreviewButton.disabled=compiledApiTools.length===0;}});
apiExecuteButton.addEventListener('click',async()=>{if(!currentPreview?.previewFingerprint)return;apiExecuteButton.disabled=true;status.textContent='Re-discovering the contract and verifying the preview fingerprint before execution…';try{const args=parseApiArguments();const data=await chrome.runtime.sendMessage({type:'execute-api-tool',operationName:apiOperation.value,arguments:args,expectedFingerprint:currentPreview.previewFingerprint,approved:!currentPreview.preview?.stateChanging||apiApproval.checked,includeWellKnownCatalog:true,maxDescriptions:3,maxTools:50});renderApiExecution(data??{ok:false,error:'No API execution response.'});status.textContent=data?.ok?'API execution received a target response and produced a local receipt.':data?.attempted?'API request was attempted, but the outcome is unknown. Do not retry automatically.':'API execution did not start.';}catch(error){renderApiExecution({ok:false,error:String(error?.message??error)});status.textContent='API execution did not start.';}finally{consumeApiPreview();}});

mcpButton.addEventListener('click',async()=>{mcpButton.disabled=true;mcpResult.hidden=true;mcpTools.hidden=true;status.textContent='Inspecting the user-authorized same-origin MCP endpoint…';try{const data=await chrome.runtime.sendMessage({type:'inspect-mcp-endpoint',endpoint:mcpEndpoint.value||'/mcp'});renderMcp(data??{ok:false,error:'No MCP inspection response.'});status.textContent='MCP inspection complete.';}catch(error){status.textContent=String(error?.message??error);mcpResult.hidden=true;mcpTools.hidden=true;}finally{mcpButton.disabled=false;}});
mcpEndpoint.addEventListener('input',()=>{mcpTools.hidden=true;invalidateMcpPreview();});
mcpListButton.addEventListener('click',async()=>{mcpListButton.disabled=true;status.textContent='Listing public modern MCP tools with credential-free bounded pagination…';try{const data=await chrome.runtime.sendMessage({type:'list-mcp-tools',endpoint:mcpEndpoint.value||'/mcp'});renderMcpTools(data??{ok:false,error:'No MCP tool-list response.'});status.textContent=data?.ok?'MCP tools compiled into local executable contracts. Select one to preview.':'MCP tools/list failed.';}catch(error){renderMcpTools({ok:false,error:String(error?.message??error)});status.textContent='MCP tools/list failed.';}finally{mcpListButton.disabled=false;}});
mcpTool.addEventListener('change',invalidateMcpPreview);mcpArguments.addEventListener('input',invalidateMcpPreview);mcpApproval.addEventListener('change',()=>{mcpExecuteButton.disabled=!currentMcpPreview||!mcpApproval.checked;});
mcpPreviewButton.addEventListener('click',async()=>{mcpPreviewButton.disabled=true;invalidateMcpPreview();status.textContent='Re-listing the live MCP tool contract and binding an exact tools/call preview…';try{const data=await chrome.runtime.sendMessage({type:'preview-mcp-tool',endpoint:mcpEndpoint.value||'/mcp',toolName:mcpTool.value,arguments:parseObject(mcpArguments.value,'MCP arguments')});renderMcpPreview(data??{ok:false,error:'No MCP preview response.'});status.textContent=data?.ok?'Fresh MCP call preview created. Explicit approval is required for every tool invocation.':'MCP preview failed.';}catch(error){renderMcpPreview({ok:false,error:String(error?.message??error)});status.textContent='MCP preview failed.';}finally{mcpPreviewButton.disabled=mcpCandidates.length===0;}});
mcpExecuteButton.addEventListener('click',async()=>{if(!currentMcpPreview?.previewFingerprint||!mcpApproval.checked)return;mcpExecuteButton.disabled=true;const approvedPreview=currentMcpPreview;status.textContent='Re-discovering MCP, re-listing the tool, and verifying the preview fingerprint before invocation…';try{const data=await chrome.runtime.sendMessage({type:'execute-mcp-tool',endpoint:mcpEndpoint.value||'/mcp',toolName:mcpTool.value,arguments:parseObject(mcpArguments.value,'MCP arguments'),expectedFingerprint:approvedPreview.previewFingerprint,approved:true});renderMcpExecution(data??{ok:false,error:'No MCP execution response.'});if(data?.receipt?.inputRequired&&data?.continuation){beginMcpContinuation(approvedPreview.preview,approvedPreview.previewFingerprint,data);status.textContent=data.continuation.continuationSupported?'MCP needs explicit user input. Review and preview the continuation round.':'MCP requested a client capability KATA does not support; no continuation was sent.';}else{clearMcpContinuation();status.textContent=data?.receipt?'MCP tool invocation produced a local receipt.':'MCP tool execution did not start.';}}catch(error){renderMcpExecution({ok:false,error:String(error?.message??error)});clearMcpContinuation();status.textContent='MCP tool execution did not start.';}finally{clearMcpPreview();}});

mcpInputResponses.addEventListener('input',clearMcpContinuationPreview);
mcpContinuationApproval.addEventListener('change',()=>{mcpContinuationExecuteButton.disabled=!currentMcpContinuation||!mcpContinuationApproval.checked;});
mcpContinuationPreviewButton.addEventListener('click',async()=>{if(!mcpInteraction)return;mcpContinuationPreviewButton.disabled=true;clearMcpContinuationPreview();status.textContent='Validating the current MCP form response and binding a continuation preview…';try{await assertMcpContinuationContext(mcpInteraction.originalPreview);const responses=parseObject(mcpInputResponses.value,'MCP inputResponses');const preview=buildMcpInputContinuationPreview(mcpInteraction.originalPreview,mcpInteraction.originalFingerprint,mcpInteraction.inputRequiredResult,responses,{round:mcpInteraction.round,maxRounds:mcpInteraction.maxRounds});const fingerprint=await fingerprintMcpInputContinuationPreview(preview);renderMcpContinuationPreview(preview,fingerprint);status.textContent='Continuation preview created. Explicit approval is required before this round is sent.';}catch(error){const p=document.createElement('p');p.textContent=String(error?.message??error);mcpContinuationPreview.append(p);mcpContinuationPreview.hidden=false;status.textContent='MCP continuation preview failed.';}finally{mcpContinuationPreviewButton.disabled=!mcpInteraction;}});
mcpContinuationExecuteButton.addEventListener('click',async()=>{if(!mcpInteraction||!currentMcpContinuation||!mcpContinuationApproval.checked)return;mcpContinuationExecuteButton.disabled=true;status.textContent='Verifying the continuation fingerprint and active-tab origin before sending this round…';try{await assertMcpContinuationContext(mcpInteraction.originalPreview);const execution=await executeModernMcpToolContinuation(mcpInteraction.originalPreview,currentMcpContinuation.preview,currentMcpContinuation.fingerprint,{approved:true,expectedFingerprint:currentMcpContinuation.fingerprint});renderMcpExecution(execution);if(execution?.receipt?.inputRequired&&execution?.continuation){beginMcpContinuation(mcpInteraction.originalPreview,mcpInteraction.originalFingerprint,execution);status.textContent=execution.continuation.continuationSupported?'MCP requires another explicit input round. Review the new request before continuing.':'MCP requested an unsupported client capability; the interaction stopped safely.';}else{clearMcpContinuation();status.textContent=execution?.ok?'MCP multi-round tool call completed with a local receipt.':execution?.receipt?.roundLimitReached?'MCP interaction reached the bounded round limit and stopped.':'MCP continuation completed without an executable success result.';}}catch(error){renderMcpExecution({ok:false,error:String(error?.message??error)});clearMcpContinuationPreview();status.textContent='MCP continuation did not execute.';}});
