const byId=id=>document.getElementById(id);
const status=byId('status'),result=byId('result'),runtimeList=byId('runtime'),diagnosis=byId('diagnosis'),blockers=byId('blockers'),button=byId('inspect'),intent=byId('intent');
const apiButton=byId('compile-api-tools'),apiResult=byId('api-tools-result'),apiSummary=byId('api-tools-summary'),apiOperation=byId('api-operation'),apiArguments=byId('api-arguments'),apiPreviewButton=byId('preview-api-request'),apiPreviewResult=byId('api-preview-result'),apiApprovalLabel=byId('api-approval-label'),apiApproval=byId('api-execution-approval'),apiExecuteButton=byId('execute-api-request'),apiExecutionResult=byId('api-execution-result');
const mcpButton=byId('inspect-mcp'),mcpEndpoint=byId('mcp-endpoint'),mcpResult=byId('mcp-result'),mcpSummary=byId('mcp-summary');
let compiledApiTools=[],currentPreview=null;

function clear(node){while(node.firstChild)node.removeChild(node.firstChild);}
function addPair(term,value){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=term;dd.textContent=value??'Unknown';runtimeList.append(dt,dd);}
function render(data){
  clear(runtimeList);clear(diagnosis);clear(blockers);const r=data.runtime??{};
  addPair('Page',r.url??'Unavailable');addPair('Secure context',String(Boolean(r.secureContext)));addPair('Frameworks',(r.frameworkHints??[]).map(x=>x.name).join(', ')||'No framework marker established');addPair('Open shadow roots',String(r.dom?.openShadowRoots??0));addPair('Iframes',String(r.dom?.iframes??0));
  if(data.ok){const d=data.diagnosis??{};const strong=document.createElement('strong'),p=document.createElement('p');strong.textContent=`${d.status??'unknown'} · ${d.primaryPath??'unknown'}`;p.textContent=d.recommendedAction??'No recommendation returned.';diagnosis.append(strong,p);for(const item of d.blockers??[]){const li=document.createElement('li'),title=document.createElement('strong'),reason=document.createElement('p'),remediation=document.createElement('p');title.textContent=item.code??'Restriction';reason.textContent=item.reason??'';remediation.textContent=item.remediation??'';li.append(title,reason,remediation);blockers.append(li);}if(!(d.blockers??[]).length){const li=document.createElement('li');li.textContent='No blocking condition was established from the observed evidence.';blockers.append(li);}status.textContent='Inspection complete.';}else{const p=document.createElement('p');p.textContent=data.error??'Inspection failed.';diagnosis.append(p);status.textContent='Local inspection completed, but KATA diagnosis was unavailable.';}result.hidden=false;
}
function invalidateApiPreview(){currentPreview=null;clear(apiPreviewResult);clear(apiExecutionResult);apiPreviewResult.hidden=true;apiExecutionResult.hidden=true;apiApproval.checked=false;apiApprovalLabel.hidden=true;apiExecuteButton.disabled=true;}
function parseApiArguments(){let value;try{value=JSON.parse(apiArguments.value||'{}');}catch{throw new Error('API arguments must be valid JSON.');}if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('API arguments must be a JSON object.');return value;}
function populateApiOperations(tools){clear(apiOperation);for(const tool of tools){const option=document.createElement('option');option.value=tool.name;option.textContent=`${tool.name} — ${tool.execution?.method??'?'}`;apiOperation.append(option);}apiPreviewButton.disabled=tools.length===0;}
function renderApiTools(data){
  clear(apiSummary);invalidateApiPreview();compiledApiTools=[];if(!data?.ok){const p=document.createElement('p');p.textContent=data?.error??'API tool compilation failed.';apiSummary.append(p);apiResult.hidden=false;populateApiOperations([]);return;}
  const compilation=data.compilation??{},tools=compilation.tools??[],rejected=compilation.rejected??[];compiledApiTools=tools;
  const headline=document.createElement('strong'),note=document.createElement('p'),list=document.createElement('ul');
  headline.textContent=`${tools.length} tool contract${tools.length===1?'':'s'} compiled locally`;
  note.textContent=`${rejected.length} operation${rejected.length===1?' was':'s were'} rejected because KATA could not establish a safe, complete agent contract. Compilation itself executes nothing.`;
  for(const tool of tools.slice(0,25)){const li=document.createElement('li'),name=document.createElement('strong'),meta=document.createElement('span');name.textContent=tool.name;meta.textContent=` — ${tool.execution?.method??'?'} · ${tool.execution?.requiresAuthorization?'declared authorization':'no declared authorization'}${(tool.execution?.streamingMedia??[]).length?` · stream ${(tool.execution.streamingMedia??[]).join(', ')}`:''}`;li.append(name,meta);list.append(li);}
  apiSummary.append(headline,note,list);populateApiOperations(tools);apiResult.hidden=false;
}
function renderApiPreview(data){
  clear(apiPreviewResult);invalidateApiPreview();if(!data?.ok){const p=document.createElement('p');p.textContent=data?.error??'API request preview failed.';apiPreviewResult.append(p);apiPreviewResult.hidden=false;return;}
  currentPreview=data;const p=data.preview??{},title=document.createElement('strong'),pre=document.createElement('pre'),note=document.createElement('p');
  title.textContent=`${p.method??'?'} · ${p.readyToExecute?'eligible for explicit execution':'not executable'}`;
  pre.textContent=JSON.stringify({url:p.url,credentialMode:p.credentialMode,stateChanging:p.stateChanging,redirect:p.redirect,timeoutMs:p.timeoutMs,maxResponseBytes:p.maxResponseBytes,headers:p.headers,body:p.body,previewFingerprint:data.previewFingerprint,blockedReason:p.blockedReason},null,2);
  note.textContent=p.requiresAuthorization?'The site declares authorization. KATA will use only browser-managed same-origin credentials; it will not read or expose them.':'No authorization is declared. KATA will omit ambient browser credentials.';
  apiPreviewResult.append(title,note,pre);apiPreviewResult.hidden=false;apiApprovalLabel.hidden=!p.stateChanging;apiExecuteButton.disabled=!p.readyToExecute||(p.stateChanging&&!apiApproval.checked);
}
function renderApiExecution(data){
  clear(apiExecutionResult);const title=document.createElement('strong'),pre=document.createElement('pre');
  if(!data?.ok){title.textContent='Execution did not start or could not be verified';pre.textContent=data?.error??'API execution failed.';}else{const receipt=data.receipt??{},response=data.response??{};title.textContent=`${receipt.outcome??'unknown'} · HTTP ${receipt.status??'no response'}`;pre.textContent=JSON.stringify({receipt,response:{ok:response.ok,status:response.status,statusText:response.statusText,url:response.url,contentType:response.contentType,bytes:response.bytes,truncated:response.truncated,outcome:response.outcome,networkError:response.networkError,bodyText:response.bodyText}},null,2);}
  apiExecutionResult.append(title,pre);apiExecutionResult.hidden=false;
}
function renderMcp(data){
  clear(mcpSummary);const strong=document.createElement('strong'),p=document.createElement('p'),recommendation=document.createElement('p'),pre=document.createElement('pre');const e=data.environment??{};
  strong.textContent=`${e.mcpEndpoint??'unknown'} · ${e.mcpModernProtocol??'unknown'} · auth ${e.mcpAuth??'unknown'}`;
  p.textContent=data.ok?'MCP discovery evidence collected locally. No tool was invoked and no authorization flow was started.':(data.error??'MCP inspection failed.');
  const d=data.diagnosis;if(d)recommendation.textContent=`KATA: ${d.status??'unknown'} · ${d.primaryPath??'unknown'} — ${d.recommendedAction??''}`;else if(data.diagnosisError)recommendation.textContent=`KATA diagnosis unavailable: ${data.diagnosisError}`;
  const local={endpoint:data.endpoint??null,server:data.server??null,authorization:data.authorization??null,environment:e};pre.textContent=JSON.stringify(local,null,2);mcpSummary.append(strong,p,recommendation,pre);mcpResult.hidden=false;
}

button.addEventListener('click',async()=>{button.disabled=true;result.hidden=true;status.textContent='Inspecting the explicitly authorized active tab…';try{render(await chrome.runtime.sendMessage({type:'inspect-active-tab',intent:intent.value})??{ok:false,error:'No response from the KATA extension service worker.'});}catch(error){status.textContent=String(error?.message??error);result.hidden=true;}finally{button.disabled=false;}});
apiButton.addEventListener('click',async()=>{apiButton.disabled=true;apiResult.hidden=true;status.textContent='Discovering API descriptions and compiling local agent contracts…';try{const data=await chrome.runtime.sendMessage({type:'compile-api-tools',includeWellKnownCatalog:true,maxDescriptions:3,maxTools:50});renderApiTools(data??{ok:false,error:'No API compiler response.'});status.textContent='API agent contracts compiled locally. Select one to generate an exact execution preview.';}catch(error){status.textContent=String(error?.message??error);apiResult.hidden=true;}finally{apiButton.disabled=false;}});
apiOperation.addEventListener('change',invalidateApiPreview);apiArguments.addEventListener('input',invalidateApiPreview);apiApproval.addEventListener('change',()=>{apiExecuteButton.disabled=!currentPreview?.preview?.readyToExecute||(currentPreview?.preview?.stateChanging&&!apiApproval.checked);});
apiPreviewButton.addEventListener('click',async()=>{apiPreviewButton.disabled=true;invalidateApiPreview();status.textContent='Re-discovering the live API contract and binding an exact request preview…';try{const data=await chrome.runtime.sendMessage({type:'preview-api-tool',operationName:apiOperation.value,arguments:parseApiArguments(),includeWellKnownCatalog:true,maxDescriptions:3,maxTools:50});renderApiPreview(data??{ok:false,error:'No API preview response.'});status.textContent=data?.ok?'Fresh API request preview created. Review it before executing.':'API request preview failed.';}catch(error){renderApiPreview({ok:false,error:String(error?.message??error)});status.textContent='API request preview failed.';}finally{apiPreviewButton.disabled=compiledApiTools.length===0;}});
apiExecuteButton.addEventListener('click',async()=>{if(!currentPreview?.previewFingerprint)return;apiExecuteButton.disabled=true;status.textContent='Re-discovering the contract and verifying the preview fingerprint before execution…';try{const args=parseApiArguments();const data=await chrome.runtime.sendMessage({type:'execute-api-tool',operationName:apiOperation.value,arguments:args,expectedFingerprint:currentPreview.previewFingerprint,approved:!currentPreview.preview?.stateChanging||apiApproval.checked,includeWellKnownCatalog:true,maxDescriptions:3,maxTools:50});renderApiExecution(data??{ok:false,error:'No API execution response.'});status.textContent=data?.ok?'API execution completed with a local receipt.':'API execution did not complete.';}catch(error){renderApiExecution({ok:false,error:String(error?.message??error)});status.textContent='API execution did not complete.';}finally{invalidateApiPreview();}});
mcpButton.addEventListener('click',async()=>{mcpButton.disabled=true;mcpResult.hidden=true;status.textContent='Inspecting the user-authorized same-origin MCP endpoint…';try{const data=await chrome.runtime.sendMessage({type:'inspect-mcp-endpoint',endpoint:mcpEndpoint.value||'/mcp'});renderMcp(data??{ok:false,error:'No MCP inspection response.'});status.textContent='MCP inspection complete.';}catch(error){status.textContent=String(error?.message??error);mcpResult.hidden=true;}finally{mcpButton.disabled=false;}});
