import {inspectBrowserRuntime} from '../src/runtime-probe.js';
import {discoverBrowserApis} from '../src/api-discovery.js';
import {compileOpenApiCandidates} from '../src/api-adapter.js';
import {buildAuthorizedExecutionPreview,fingerprintExecutionPreview,executionRequestFromPreview,executePageApiRequest} from '../src/api-execution.js';
import {listModernMcpTools,buildMcpToolCallPreview,buildMcpInputRequiredResumePreview,fingerprintMcpToolCallPreview,executeModernMcpToolCall,executeModernMcpToolResume,getModernMcpTask,buildMcpTaskUpdatePreview,executeModernMcpTaskUpdate,buildMcpTaskCancelPreview,executeModernMcpTaskCancel} from '../src/mcp-adapter.js';
import {normalizeMcpTraceContext} from '../lib/shared/mcp-trace-context.js';

export {executePageApiRequest};

const KATA_BASE='https://kata-webmcp.vercel.app';
const MCP_VERSION='2026-07-28';
const MCP_SERVER_INFO_KEY='io.modelcontextprotocol/serverInfo';
const INTENTS=new Set(['read','act','automate','expose_webmcp','call_api','connect_mcp']);

function assertIntent(intent){if(!INTENTS.has(intent))throw new Error(`Unsupported interoperability intent: ${intent}`);}
function tabUrl(tab){if(!Number.isInteger(tab?.id))throw new Error('An active browser tab is required.');try{return new URL(String(tab.url??''));}catch{throw new Error('The active tab does not expose a valid HTTP(S) URL.');}}
function assertInspectableTab(tab){const url=tabUrl(tab);if(url.protocol!=='https:'&&url.protocol!=='http:')throw new Error('KATA only inspects explicitly authorized HTTP(S) pages.');return url;}
function isLoopback(hostname){const h=String(hostname).toLowerCase();return h==='localhost'||h==='::1'||h==='[::1]'||h==='127.0.0.1'||h.startsWith('127.');}
function resolveMcpEndpoint(tab,endpoint){const page=assertInspectableTab(tab);const target=new URL(String(endpoint||'/mcp'),page.origin);if(target.origin!==page.origin)throw new Error('MCP inspection is restricted to a same-origin endpoint on the explicitly authorized tab.');if(target.protocol!=='https:'&&!(target.protocol==='http:'&&isLoopback(target.hostname)))throw new Error('Remote MCP inspection requires HTTPS; cleartext HTTP is allowed only for loopback development endpoints.');target.hash='';return target;}
function localFailure(error,probe){return{ok:false,error:String(error?.message??error),runtime:probe?.runtime??null,evidence:probe?.evidence??[]};}
function discoverBody(traceContext=null){return{jsonrpc:'2.0',id:'kata-mcp-discover',method:'server/discover',params:{_meta:{'io.modelcontextprotocol/protocolVersion':MCP_VERSION,'io.modelcontextprotocol/clientCapabilities':{},'io.modelcontextprotocol/clientInfo':{name:'kata-interop-inspector',version:'3.0.0'},...(traceContext??{})}}};}
function validMcpServerInfo(value){if(!value||typeof value!=='object'||Array.isArray(value)||typeof value.name!=='string'||!value.name.trim()||(value.version!==undefined&&typeof value.version!=='string'))return null;return{name:value.name,...(value.version!==undefined?{version:value.version}:{})};}
function discoveredMcpServerInfo(result){const metadata=result?._meta;if(metadata&&typeof metadata==='object'&&!Array.isArray(metadata)&&Object.prototype.hasOwnProperty.call(metadata,MCP_SERVER_INFO_KEY))return validMcpServerInfo(metadata[MCP_SERVER_INFO_KEY]);return validMcpServerInfo(result?.serverInfo);}
function resourceMetadataUrl(value){const match=String(value??'').match(/(?:^|[,\s])resource_metadata=(?:"([^"]+)"|([^,\s]+))/i);return match?.[1]??match?.[2]??null;}
async function readProtectedResourceMetadata(response,target,fetchImpl){
  const raw=resourceMetadataUrl(response?.headers?.get?.('www-authenticate'));if(!raw)return{state:'unverified',metadata:null};
  let url;try{url=new URL(raw,target);}catch{return{state:'unverified',metadata:null};}
  if(url.origin!==target.origin||url.protocol!==target.protocol)return{state:'unverified',metadata:null};
  let metadataResponse;try{metadataResponse=await fetchImpl(url.href,{method:'GET',headers:{Accept:'application/json'},credentials:'omit',cache:'no-store',redirect:'manual'});}catch{return{state:'unverified',metadata:null};}
  if(!metadataResponse?.ok)return{state:'unverified',metadata:null};let metadata;try{metadata=await metadataResponse.json();}catch{return{state:'unverified',metadata:null};}
  if(!metadata||typeof metadata!=='object'||!Array.isArray(metadata.authorization_servers))return{state:'unverified',metadata:null};
  return{state:'available',metadata:{resource:typeof metadata.resource==='string'?metadata.resource:null,authorizationServers:metadata.authorization_servers.filter(x=>typeof x==='string').slice(0,16),scopesSupported:Array.isArray(metadata.scopes_supported)?metadata.scopes_supported.filter(x=>typeof x==='string').slice(0,64):[]}};
}

export async function inspectMcpEndpoint(tab,endpoint='/mcp',deps={}){
  const traceContext=normalizeMcpTraceContext(deps.traceContext);
  const fetchImpl=deps.fetchImpl??globalThis.fetch;if(typeof fetchImpl!=='function')throw new Error('fetch is unavailable.');const target=resolveMcpEndpoint(tab,endpoint);
  const init={method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json, text/event-stream','MCP-Protocol-Version':MCP_VERSION,'Mcp-Method':'server/discover'},body:JSON.stringify(discoverBody(traceContext)),credentials:'omit',cache:'no-store',redirect:'manual'};
  let response;try{response=await fetchImpl(target.href,init);}catch(error){return{ok:false,error:`MCP discovery request failed: ${error?.message??error}`,environment:{mcpEndpoint:'unknown',mcpModernProtocol:'unknown',mcpAuth:'unknown',mcpAuthMetadata:'unknown'}};}
  if(response?.status===401){const authorization=await readProtectedResourceMetadata(response,target,fetchImpl);return{ok:true,endpoint:target.href,environment:{mcpEndpoint:'protected',mcpModernProtocol:'unknown',mcpAuth:'required',mcpAuthMetadata:authorization.state},authorization:authorization.metadata};}
  let payload=null;try{payload=await response?.json?.();}catch{}
  if(response?.ok&&payload?.jsonrpc==='2.0'&&payload?.result&&Array.isArray(payload.result.supportedVersions)){const supported=payload.result.supportedVersions.includes(MCP_VERSION);return{ok:true,endpoint:target.href,environment:{mcpEndpoint:'available',mcpModernProtocol:supported?'supported':'unsupported',mcpAuth:'none',mcpAuthMetadata:'not-required'},server:{supportedVersions:payload.result.supportedVersions.slice(0,32),capabilities:payload.result.capabilities??{},serverInfo:discoveredMcpServerInfo(payload.result),instructions:typeof payload.result.instructions==='string'?payload.result.instructions:null}};}
  if(payload?.error?.code===-32601)return{ok:true,endpoint:target.href,environment:{mcpEndpoint:'legacy-candidate',mcpModernProtocol:'unsupported',mcpAuth:'unknown',mcpAuthMetadata:'unknown'},server:null};
  return{ok:false,error:`MCP server/discover was not established (HTTP ${response?.status??'unknown'}).`,endpoint:target.href,environment:{mcpEndpoint:'unknown',mcpModernProtocol:'unknown',mcpAuth:'unknown',mcpAuthMetadata:'unknown'}};
}

export async function diagnoseMcpEvidence(mcpEnvironment,deps={}){
  const fetchImpl=deps.fetchImpl??globalThis.fetch;const kataBase=String(deps.kataBase??KATA_BASE).replace(/\/$/,'');if(typeof fetchImpl!=='function')throw new Error('fetch is unavailable.');
  const environment={webMcpApi:'unknown',frame:'top',toolsPermission:'unknown',originExposure:'not-required',api:'unknown',auth:'unknown',cors:'unknown',cspConnect:'unknown',rateLimit:'unknown',botProtection:'unknown',terms:'unknown',userAuthorizedBrowserFlow:true,...mcpEnvironment};
  const response=await fetchImpl(`${kataBase}/api/invoke`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'kata_diagnose_web_interop',arguments:{intent:'connect_mcp',environment}}),credentials:'omit',cache:'no-store'});
  if(!response?.ok)throw new Error(`KATA diagnosis service returned HTTP ${response?.status??'unknown'}.`);const payload=await response.json();if(!payload?.ok||!payload?.result)throw new Error('KATA diagnosis service returned an invalid diagnosis payload.');return payload.result;
}

async function assertPublicModernMcp(tab,endpoint,deps={}){const discovery=await inspectMcpEndpoint(tab,endpoint,deps);if(!discovery.ok)throw new Error(discovery.error??'MCP endpoint discovery failed.');if(discovery.environment?.mcpAuth==='required')throw new Error('MCP authorization is required. KATA will not start OAuth or borrow browser credentials in this execution path.');if(discovery.environment?.mcpModernProtocol!=='supported')throw new Error('This execution path requires a modern MCP 2026-07-28 endpoint. Legacy MCP remains inspection-only.');if(discovery.server?.capabilities?.tools===undefined)throw new Error('The MCP server does not advertise the tools capability.');return discovery;}

export async function listAuthorizedTabMcpTools(tab,endpoint='/mcp',options={},deps={}){const target=resolveMcpEndpoint(tab,endpoint);const traceContext=normalizeMcpTraceContext(options.traceContext);const discovery=await assertPublicModernMcp(tab,target.href,{...deps,traceContext});const inventory=await listModernMcpTools(target.href,{fetchImpl:deps.fetchImpl??globalThis.fetch,maxPages:options.maxPages??8,maxTools:options.maxTools??100,maxResponseBytes:options.maxResponseBytes,timeoutMs:options.timeoutMs,signal:options.signal,traceContext});return{ok:true,endpoint:target.href,server:{serverInfo:discovery.server?.serverInfo??null,capabilities:discovery.server?.capabilities??{}},inventory};}
async function freshMcpCandidate(tab,endpoint,toolName,options,deps){if(typeof toolName!=='string'||!toolName)throw new TypeError('An MCP tool name is required.');const listed=await listAuthorizedTabMcpTools(tab,endpoint,options,deps);const matches=(listed.inventory?.tools??[]).filter(tool=>tool.name===toolName);if(matches.length!==1)throw new Error(matches.length?`MCP tool name is ambiguous: ${toolName}`:`MCP tool is no longer available: ${toolName}`);return{listed,candidate:matches[0]};}
export async function previewAuthorizedTabMcpTool(tab,endpoint,toolName,args={},options={},deps={}){const {listed,candidate}=await freshMcpCandidate(tab,endpoint,toolName,options,deps);const preview=buildMcpToolCallPreview(candidate,args,listed.endpoint,{maxResponseBytes:options.maxResponseBytes,timeoutMs:options.timeoutMs,traceContext:options.traceContext});const previewFingerprint=await fingerprintMcpToolCallPreview(preview,deps.cryptoImpl??globalThis.crypto);return{ok:true,preview,previewFingerprint,tool:{name:candidate.name,title:candidate.title,description:candidate.description},cache:listed.inventory.cache};}
export async function executeAuthorizedTabMcpTool(tab,endpoint,toolName,args={},expectedFingerprint,options={},deps={}){if(options.approved!==true)throw new Error('Explicit approval is required before an MCP tool can execute.');const fresh=await previewAuthorizedTabMcpTool(tab,endpoint,toolName,args,options,deps);if(typeof expectedFingerprint!=='string'||expectedFingerprint!==fresh.previewFingerprint)throw new Error('MCP tool preview fingerprint is stale or does not match the freshly discovered tool contract.');const execution=await executeModernMcpToolCall(fresh.preview,fresh.previewFingerprint,{approved:true,expectedFingerprint,fetchImpl:deps.fetchImpl??globalThis.fetch,cryptoImpl:deps.cryptoImpl??globalThis.crypto,signal:options.signal});return{...execution,attempted:true};}

function pendingInputRequired(continuation){if(!continuation||typeof continuation!=='object'||!Number.isInteger(continuation.round)||!continuation.inputRequests||typeof continuation.inputRequests!=='object')throw new TypeError('A valid MCP input_required continuation is required.');return{resultType:'input_required',inputRequests:continuation.inputRequests,requestState:continuation.requestState??null};}
export async function previewAuthorizedTabMcpResume(tab,endpoint,toolName,args={},continuation,inputResponses,options={},deps={}){const fresh=await previewAuthorizedTabMcpTool(tab,endpoint,toolName,args,options,deps);const preview=buildMcpInputRequiredResumePreview(fresh.preview,pendingInputRequired(continuation),inputResponses,{round:continuation.round});const previewFingerprint=await fingerprintMcpToolCallPreview(preview,deps.cryptoImpl??globalThis.crypto);return{ok:true,preview,previewFingerprint,tool:fresh.tool,continuationRound:continuation.round};}
export async function executeAuthorizedTabMcpResume(tab,endpoint,toolName,args={},continuation,inputResponses,expectedFingerprint,options={},deps={}){if(options.approved!==true)throw new Error('Explicit approval is required before an MCP input_required round can resume.');const fresh=await previewAuthorizedTabMcpResume(tab,endpoint,toolName,args,continuation,inputResponses,options,deps);if(typeof expectedFingerprint!=='string'||expectedFingerprint!==fresh.previewFingerprint)throw new Error('MCP resume preview fingerprint is stale or does not match the freshly discovered tool contract and current input round.');const execution=await executeModernMcpToolResume(fresh.preview,fresh.previewFingerprint,{approved:true,expectedFingerprint,fetchImpl:deps.fetchImpl??globalThis.fetch,cryptoImpl:deps.cryptoImpl??globalThis.crypto,signal:options.signal});return{...execution,attempted:true};}

function taskForEndpoint(tab,endpoint,task){const target=resolveMcpEndpoint(tab,endpoint);if(!task||typeof task!=='object')throw new TypeError('A local MCP task handle is required.');if(task.endpoint&&new URL(String(task.endpoint)).href!==target.href)throw new Error('MCP task endpoint does not match the explicitly authorized same-origin endpoint.');return{...task,endpoint:target.href};}
export async function getAuthorizedTabMcpTask(tab,endpoint,task,options={},deps={}){const local=taskForEndpoint(tab,endpoint,task);return getModernMcpTask(local,{fetchImpl:deps.fetchImpl??globalThis.fetch,signal:options.signal,maxResponseBytes:options.maxResponseBytes,timeoutMs:options.timeoutMs});}
export async function previewAuthorizedTabMcpTaskUpdate(tab,endpoint,task,inputResponses,options={},deps={}){const local=taskForEndpoint(tab,endpoint,task);const preview=buildMcpTaskUpdatePreview(local,inputResponses,{maxResponseBytes:options.maxResponseBytes,timeoutMs:options.timeoutMs});const previewFingerprint=await fingerprintMcpToolCallPreview(preview,deps.cryptoImpl??globalThis.crypto);return{ok:true,preview,previewFingerprint};}
export async function executeAuthorizedTabMcpTaskUpdate(tab,endpoint,task,inputResponses,expectedFingerprint,options={},deps={}){if(options.approved!==true)throw new Error('Explicit approval is required before MCP task input can be submitted.');const fresh=await previewAuthorizedTabMcpTaskUpdate(tab,endpoint,task,inputResponses,options,deps);if(typeof expectedFingerprint!=='string'||expectedFingerprint!==fresh.previewFingerprint)throw new Error('MCP task update preview fingerprint is stale or does not match.');return executeModernMcpTaskUpdate(fresh.preview,fresh.previewFingerprint,{approved:true,expectedFingerprint,fetchImpl:deps.fetchImpl??globalThis.fetch,cryptoImpl:deps.cryptoImpl??globalThis.crypto,signal:options.signal});}
export async function previewAuthorizedTabMcpTaskCancel(tab,endpoint,task,options={},deps={}){const local=taskForEndpoint(tab,endpoint,task);const preview=buildMcpTaskCancelPreview(local,{maxResponseBytes:options.maxResponseBytes,timeoutMs:options.timeoutMs});const previewFingerprint=await fingerprintMcpToolCallPreview(preview,deps.cryptoImpl??globalThis.crypto);return{ok:true,preview,previewFingerprint};}
export async function executeAuthorizedTabMcpTaskCancel(tab,endpoint,task,expectedFingerprint,options={},deps={}){if(options.approved!==true)throw new Error('Explicit approval is required before an MCP task can be cancelled.');const fresh=await previewAuthorizedTabMcpTaskCancel(tab,endpoint,task,options,deps);if(typeof expectedFingerprint!=='string'||expectedFingerprint!==fresh.previewFingerprint)throw new Error('MCP task cancel preview fingerprint is stale or does not match.');return executeModernMcpTaskCancel(fresh.preview,fresh.previewFingerprint,{approved:true,expectedFingerprint,fetchImpl:deps.fetchImpl??globalThis.fetch,cryptoImpl:deps.cryptoImpl??globalThis.crypto,signal:options.signal});}

async function runtimeProbeForTab(tab,chromeApi){assertInspectableTab(tab);if(!chromeApi?.scripting?.executeScript)throw new Error('chrome.scripting is unavailable.');const injected=await chromeApi.scripting.executeScript({target:{tabId:tab.id},world:'MAIN',func:inspectBrowserRuntime,args:[{}]});const probe=injected?.[0]?.result;if(!probe?.environment||!probe?.runtime)throw new Error('The page runtime probe did not return a valid KATA evidence snapshot.');return probe;}

export async function compileAuthorizedTabApiTools(tab,options={},deps={}){const chromeApi=deps.chromeApi??globalThis.chrome,fetchImpl=deps.fetchImpl??globalThis.fetch;assertInspectableTab(tab);if(typeof fetchImpl!=='function')throw new Error('fetch is unavailable.');const probe=await runtimeProbeForTab(tab,chromeApi);const discovery=await discoverBrowserApis({declaredApiDescriptions:probe.runtime.declaredApiDescriptions,includeWellKnownCatalog:options.includeWellKnownCatalog!==false,maxDescriptions:options.maxDescriptions??3,signal:options.signal},{origin:probe.runtime.origin,fetch:fetchImpl});const compilation=compileOpenApiCandidates(discovery,{maxTools:options.maxTools??50});return{ok:true,compilation,discovery:{descriptions:discovery.descriptions,resources:discovery.resources,evidence:discovery.evidence,limits:discovery.limits},runtime:{origin:probe.runtime.origin},evidence:probe.evidence??[]};}
async function freshApiCandidate(tab,operationName,options,deps){if(typeof operationName!=='string'||!operationName)throw new TypeError('A compiled OpenAPI operation name is required.');const compiled=await compileAuthorizedTabApiTools(tab,options,deps);const matches=(compiled.compilation?.tools??[]).filter(tool=>tool?.name===operationName);if(matches.length!==1)throw new Error(matches.length?`OpenAPI operation name is ambiguous: ${operationName}`:`OpenAPI operation is no longer available: ${operationName}`);return{compiled,candidate:matches[0]};}
export async function previewAuthorizedTabApiExecution(tab,operationName,args={},options={},deps={}){const page=assertInspectableTab(tab),{compiled,candidate}=await freshApiCandidate(tab,operationName,options,deps);const preview=buildAuthorizedExecutionPreview(candidate,args,compiled.runtime?.origin??page.origin,options);const previewFingerprint=await fingerprintExecutionPreview(preview,deps.cryptoImpl??globalThis.crypto);return{ok:true,preview,previewFingerprint,operation:{name:candidate.name,description:candidate.description??null},evidence:compiled.evidence??[]};}
export async function executeAuthorizedTabApiExecution(tab,operationName,args={},expectedFingerprint,options={},deps={}){if(options.approved!==true)throw new Error('Explicit approval is required before an API operation can execute.');const fresh=await previewAuthorizedTabApiExecution(tab,operationName,args,options,deps);if(typeof expectedFingerprint!=='string'||expectedFingerprint!==fresh.previewFingerprint)throw new Error('Execution preview fingerprint is stale or does not match the freshly discovered API contract.');if(!fresh.preview.readyToExecute)throw new Error(`API execution is blocked: ${fresh.preview.blockedReason??'policy_blocked'}`);const chromeApi=deps.chromeApi??globalThis.chrome;if(!chromeApi?.scripting?.executeScript)throw new Error('chrome.scripting is unavailable.');const request=executionRequestFromPreview(fresh.preview);const injected=await chromeApi.scripting.executeScript({target:{tabId:tab.id},world:'MAIN',func:executePageApiRequest,args:[request]});const response=injected?.[0]?.result;if(!response||typeof response!=='object')throw new Error('The page API executor did not return a valid bounded result.');const receipt={previewFingerprint:fresh.previewFingerprint,operationName,method:fresh.preview.method,stateChanging:fresh.preview.stateChanging,requiresAuthorization:fresh.preview.requiresAuthorization,status:response.status??null,targetOk:Boolean(response.ok),outcome:response.outcome??'unknown',bytes:Number(response.bytes??0),contentType:response.contentType??null,truncated:Boolean(response.truncated),durationMs:Number(response.durationMs??0)};const completed=receipt.outcome==='completed';return{ok:completed,attempted:true,error:completed?null:`API execution outcome is unknown${response.networkError?`: ${response.networkError}`:''}. Do not retry automatically because the target may have committed the operation.`,receipt,response};}

export async function inspectAuthorizedTab(tab,intent='read',deps={}){const chromeApi=deps.chromeApi??globalThis.chrome;const fetchImpl=deps.fetchImpl??globalThis.fetch;const kataBase=String(deps.kataBase??KATA_BASE).replace(/\/$/,'');assertIntent(intent);assertInspectableTab(tab);if(typeof fetchImpl!=='function')throw new Error('fetch is unavailable.');const probe=await runtimeProbeForTab(tab,chromeApi);const environment={...probe.environment,userAuthorizedBrowserFlow:true};const body={name:'kata_diagnose_web_interop',arguments:{intent,environment}};let response;try{response=await fetchImpl(`${kataBase}/api/invoke`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),credentials:'omit',cache:'no-store'});}catch(error){return localFailure(new Error(`KATA diagnosis request failed: ${error?.message??error}`),probe);}if(!response?.ok)return localFailure(new Error(`KATA diagnosis service returned HTTP ${response?.status??'unknown'}.`),probe);let payload;try{payload=await response.json();}catch{return localFailure(new Error('KATA diagnosis service returned an invalid JSON response.'),probe);}if(!payload?.ok||!payload?.result)return localFailure(new Error('KATA diagnosis service returned an invalid diagnosis payload.'),probe);return{ok:true,runtime:probe.runtime,evidence:probe.evidence??[],diagnosis:payload.result};}

async function activeTab(){const tabs=await globalThis.chrome.tabs.query({active:true,currentWindow:true});return tabs?.[0];}
async function inspectFromPopup(message){return inspectAuthorizedTab(await activeTab(),message.intent??'read');}
async function inspectMcpFromPopup(message){const local=await inspectMcpEndpoint(await activeTab(),message.endpoint??'/mcp');try{return{...local,diagnosis:await diagnoseMcpEvidence(local.environment)};}catch(error){return{...local,diagnosis:null,diagnosisError:String(error?.message??error)};}}
async function listMcpToolsFromPopup(message){return listAuthorizedTabMcpTools(await activeTab(),message.endpoint??'/mcp',{maxPages:8,maxTools:100,timeoutMs:message.timeoutMs});}
async function previewMcpToolFromPopup(message){return previewAuthorizedTabMcpTool(await activeTab(),message.endpoint??'/mcp',message.toolName,message.arguments??{},{maxPages:8,maxTools:100,maxResponseBytes:message.maxResponseBytes,timeoutMs:message.timeoutMs});}
async function executeMcpToolFromPopup(message){return executeAuthorizedTabMcpTool(await activeTab(),message.endpoint??'/mcp',message.toolName,message.arguments??{},message.expectedFingerprint,{approved:message.approved===true,maxPages:8,maxTools:100,maxResponseBytes:message.maxResponseBytes,timeoutMs:message.timeoutMs});}
async function previewMcpResumeFromPopup(message){return previewAuthorizedTabMcpResume(await activeTab(),message.endpoint??'/mcp',message.toolName,message.arguments??{},message.continuation,message.inputResponses??{},{maxPages:8,maxTools:100,maxResponseBytes:message.maxResponseBytes,timeoutMs:message.timeoutMs});}
async function executeMcpResumeFromPopup(message){return executeAuthorizedTabMcpResume(await activeTab(),message.endpoint??'/mcp',message.toolName,message.arguments??{},message.continuation,message.inputResponses??{},message.expectedFingerprint,{approved:message.approved===true,maxPages:8,maxTools:100,maxResponseBytes:message.maxResponseBytes,timeoutMs:message.timeoutMs});}
async function getMcpTaskFromPopup(message){return getAuthorizedTabMcpTask(await activeTab(),message.endpoint??'/mcp',message.task,{maxResponseBytes:message.maxResponseBytes,timeoutMs:message.timeoutMs});}
async function previewMcpTaskUpdateFromPopup(message){return previewAuthorizedTabMcpTaskUpdate(await activeTab(),message.endpoint??'/mcp',message.task,message.inputResponses??{},{maxResponseBytes:message.maxResponseBytes,timeoutMs:message.timeoutMs});}
async function executeMcpTaskUpdateFromPopup(message){return executeAuthorizedTabMcpTaskUpdate(await activeTab(),message.endpoint??'/mcp',message.task,message.inputResponses??{},message.expectedFingerprint,{approved:message.approved===true,maxResponseBytes:message.maxResponseBytes,timeoutMs:message.timeoutMs});}
async function previewMcpTaskCancelFromPopup(message){return previewAuthorizedTabMcpTaskCancel(await activeTab(),message.endpoint??'/mcp',message.task,{maxResponseBytes:message.maxResponseBytes,timeoutMs:message.timeoutMs});}
async function executeMcpTaskCancelFromPopup(message){return executeAuthorizedTabMcpTaskCancel(await activeTab(),message.endpoint??'/mcp',message.task,message.expectedFingerprint,{approved:message.approved===true,maxResponseBytes:message.maxResponseBytes,timeoutMs:message.timeoutMs});}
async function compileApiFromPopup(message){return compileAuthorizedTabApiTools(await activeTab(),{includeWellKnownCatalog:message.includeWellKnownCatalog!==false,maxDescriptions:message.maxDescriptions??3,maxTools:message.maxTools??50});}
async function previewApiFromPopup(message){return previewAuthorizedTabApiExecution(await activeTab(),message.operationName,message.arguments??{},{includeWellKnownCatalog:message.includeWellKnownCatalog!==false,maxDescriptions:message.maxDescriptions??3,maxTools:message.maxTools??50,timeoutMs:message.timeoutMs,maxResponseBytes:message.maxResponseBytes});}
async function executeApiFromPopup(message){return executeAuthorizedTabApiExecution(await activeTab(),message.operationName,message.arguments??{},message.expectedFingerprint,{approved:message.approved===true,includeWellKnownCatalog:message.includeWellKnownCatalog!==false,maxDescriptions:message.maxDescriptions??3,maxTools:message.maxTools??50,timeoutMs:message.timeoutMs,maxResponseBytes:message.maxResponseBytes});}

if(globalThis.chrome?.runtime?.onMessage){globalThis.chrome.runtime.onMessage.addListener((message,_sender,sendResponse)=>{if(message?.type==='inspect-active-tab')inspectFromPopup(message).then(sendResponse,error=>sendResponse({ok:false,error:String(error?.message??error)}));else if(message?.type==='inspect-mcp-endpoint')inspectMcpFromPopup(message).then(sendResponse,error=>sendResponse({ok:false,error:String(error?.message??error)}));else if(message?.type==='list-mcp-tools')listMcpToolsFromPopup(message).then(sendResponse,error=>sendResponse({ok:false,error:String(error?.message??error)}));else if(message?.type==='preview-mcp-tool')previewMcpToolFromPopup(message).then(sendResponse,error=>sendResponse({ok:false,error:String(error?.message??error)}));else if(message?.type==='execute-mcp-tool')executeMcpToolFromPopup(message).then(sendResponse,error=>sendResponse({ok:false,error:String(error?.message??error)}));else if(message?.type==='preview-mcp-resume')previewMcpResumeFromPopup(message).then(sendResponse,error=>sendResponse({ok:false,error:String(error?.message??error)}));else if(message?.type==='execute-mcp-resume')executeMcpResumeFromPopup(message).then(sendResponse,error=>sendResponse({ok:false,error:String(error?.message??error)}));else if(message?.type==='get-mcp-task')getMcpTaskFromPopup(message).then(sendResponse,error=>sendResponse({ok:false,error:String(error?.message??error)}));else if(message?.type==='preview-mcp-task-update')previewMcpTaskUpdateFromPopup(message).then(sendResponse,error=>sendResponse({ok:false,error:String(error?.message??error)}));else if(message?.type==='execute-mcp-task-update')executeMcpTaskUpdateFromPopup(message).then(sendResponse,error=>sendResponse({ok:false,error:String(error?.message??error)}));else if(message?.type==='preview-mcp-task-cancel')previewMcpTaskCancelFromPopup(message).then(sendResponse,error=>sendResponse({ok:false,error:String(error?.message??error)}));else if(message?.type==='execute-mcp-task-cancel')executeMcpTaskCancelFromPopup(message).then(sendResponse,error=>sendResponse({ok:false,error:String(error?.message??error)}));else if(message?.type==='compile-api-tools')compileApiFromPopup(message).then(sendResponse,error=>sendResponse({ok:false,error:String(error?.message??error)}));else if(message?.type==='preview-api-tool')previewApiFromPopup(message).then(sendResponse,error=>sendResponse({ok:false,error:String(error?.message??error)}));else if(message?.type==='execute-api-tool')executeApiFromPopup(message).then(sendResponse,error=>sendResponse({ok:false,error:String(error?.message??error)}));else return false;return true;});}