import {createSessionVault,sessionVaultLimits} from './session-vault.js';
import {inspectMcpEndpoint} from './service-worker.js';
import {listModernMcpTools,buildMcpToolCallPreview,buildMcpInputRequiredResumePreview,fingerprintMcpToolCallPreview,executeModernMcpToolCall,executeModernMcpToolResume,getModernMcpTask,buildMcpTaskUpdatePreview,executeModernMcpTaskUpdate,buildMcpTaskCancelPreview,executeModernMcpTaskCancel} from '../src/mcp-adapter.js';

function safeOrigin(raw){let url;try{url=new URL(String(raw));}catch{throw new TypeError('A valid HTTP(S) origin is required.');}if(!['http:','https:'].includes(url.protocol)||url.username||url.password)throw new TypeError('A valid HTTP(S) origin is required.');return url.origin;}
function safeEndpoint(tab,raw='/mcp'){if(!Number.isInteger(tab?.id))throw new Error('An active browser tab is required.');let page;try{page=new URL(String(tab.url??''));}catch{throw new Error('The active tab does not expose a valid HTTP(S) URL.');}if(!['http:','https:'].includes(page.protocol))throw new Error('KATA only uses session authorization on HTTP(S) pages.');const target=new URL(String(raw||'/mcp'),page.origin);if(target.origin!==page.origin)throw new Error('Session-authorized MCP remains restricted to the explicitly authorized tab origin.');if(target.protocol!=='https:'&&!isLoopback(target))throw new Error('Remote MCP authorization requires HTTPS; cleartext HTTP is allowed only for loopback development.');target.hash='';return target;}
function isLoopback(url){const h=String(url.hostname).toLowerCase();return h==='localhost'||h==='127.0.0.1'||h.startsWith('127.')||h==='::1'||h==='[::1]';}
function publicBinding(descriptor){if(!descriptor||typeof descriptor!=='object')throw new TypeError('A redacted session credential descriptor is required.');return{credentialId:descriptor.credentialId,revision:descriptor.revision,origin:descriptor.origin,kind:descriptor.kind,schemeName:descriptor.schemeName??null,location:descriptor.location??null,parameterName:descriptor.parameterName??null,scopes:Array.isArray(descriptor.scopes)?[...descriptor.scopes]:[]};}
function publicTaskState(task,descriptor){return{vaultTaskId:descriptor.vaultTaskId,origin:descriptor.origin,toolName:descriptor.toolName,status:task.status??descriptor.status??null,pollIntervalMs:Number.isFinite(task.pollIntervalMs)?task.pollIntervalMs:null,ttlMs:Number.isFinite(task.ttlMs)?task.ttlMs:null,inputRequests:task.inputRequests??null,inputRequestsSupported:task.supported??true,unsupportedInputRequests:task.unsupported??[],result:task.result??null,outputValidation:task.outputValidation??null,automaticPolling:false,updatedAt:descriptor.updatedAt};}
function sanitizedTaskCreation(execution,descriptor){const task=execution.task;const result=task?{resultType:'task',status:task.status??null,pollIntervalMs:task.pollIntervalMs??null,ttlMs:task.ttlMs??null}:execution.result;return{...execution,result,task:task?{...descriptor}:null};}

export async function createBearerAuthorizedFetch(fetchImpl,vault,binding,endpoint){
  if(typeof fetchImpl!=='function')throw new Error('fetch is unavailable.');
  if(!vault?.resolveCredential)throw new Error('Session credential vault is unavailable.');
  const target=new URL(String(endpoint));const approved=publicBinding(binding);if(approved.origin!==target.origin)throw new Error('Credential origin does not match the MCP endpoint.');
  const resolved=await vault.resolveCredential(approved);
  if(resolved.kind!=='bearer-token'||typeof resolved.secret!=='string'||!resolved.secret)throw new Error('A valid session bearer token is required for protected MCP.');
  const secret=resolved.secret;
  return async(url,init={})=>{
    const requestUrl=new URL(String(url));if(requestUrl.origin!==target.origin)throw new Error('Session MCP credential cannot be sent cross-origin.');
    if(init.credentials!==undefined&&init.credentials!=='omit')throw new Error('Protected MCP must keep ambient browser credentials omitted.');
    if(init.redirect!==undefined&&init.redirect!=='manual')throw new Error('Protected MCP must keep redirects manual.');
    const headers={...(init.headers??{})};if(headers.Authorization!==undefined||headers.authorization!==undefined)throw new Error('MCP Authorization header is owned by the session broker.');
    headers.Authorization=`Bearer ${secret}`;
    return fetchImpl(requestUrl.href,{...init,headers,credentials:'omit',redirect:'manual'});
  };
}

export function createSessionBroker({storageArea=globalThis.chrome?.storage?.session,cryptoImpl=globalThis.crypto,fetchImpl=globalThis.fetch,now=()=>Date.now()}={}){
  const vault=createSessionVault(storageArea,cryptoImpl,now);
  async function authorizedFetch(binding,endpoint){return createBearerAuthorizedFetch(fetchImpl,vault,binding,endpoint);}
  async function discover(tab,endpoint,binding){const target=safeEndpoint(tab,endpoint),authFetch=await authorizedFetch(binding,target.href);const discovery=await inspectMcpEndpoint(tab,target.href,{fetchImpl:authFetch});if(!discovery.ok)throw new Error(discovery.error??'MCP endpoint discovery failed.');if(discovery.environment?.mcpModernProtocol!=='supported')throw new Error('Session-authorized execution requires a modern MCP 2026-07-28 endpoint.');if(discovery.server?.capabilities?.tools===undefined)throw new Error('The MCP server does not advertise the tools capability.');return{target,authFetch,discovery};}
  async function listMcpTools(tab,endpoint,binding,options={}){const {target,authFetch,discovery}=await discover(tab,endpoint,binding);const inventory=await listModernMcpTools(target.href,{fetchImpl:authFetch,maxPages:options.maxPages??8,maxTools:options.maxTools??100,maxResponseBytes:options.maxResponseBytes,timeoutMs:options.timeoutMs,signal:options.signal});return{ok:true,inventory,server:{serverInfo:discovery.server?.serverInfo??null,capabilities:discovery.server?.capabilities??{}}};}
  async function freshCandidate(tab,endpoint,toolName,binding,options){if(typeof toolName!=='string'||!toolName)throw new TypeError('An MCP tool name is required.');const listed=await listMcpTools(tab,endpoint,binding,options);const matches=(listed.inventory?.tools??[]).filter(tool=>tool.name===toolName);if(matches.length!==1)throw new Error(matches.length?`MCP tool name is ambiguous: ${toolName}`:`MCP tool is no longer available: ${toolName}`);return{listed,candidate:matches[0]};}
  async function previewMcpTool(tab,endpoint,toolName,args,binding,options={}){const target=safeEndpoint(tab,endpoint);const {candidate,listed}=await freshCandidate(tab,target.href,toolName,binding,options);const preview={...buildMcpToolCallPreview(candidate,args,target.href,{maxResponseBytes:options.maxResponseBytes,timeoutMs:options.timeoutMs}),authorizationBinding:publicBinding(binding)};const previewFingerprint=await fingerprintMcpToolCallPreview(preview,cryptoImpl);return{ok:true,preview,previewFingerprint,tool:{name:candidate.name,title:candidate.title,description:candidate.description},cache:listed.inventory.cache};}
  async function executeMcpTool(tab,endpoint,toolName,args,binding,expectedFingerprint,options={}){if(options.approved!==true)throw new Error('Explicit approval is required before a protected MCP tool can execute.');const fresh=await previewMcpTool(tab,endpoint,toolName,args,binding,options);if(typeof expectedFingerprint!=='string'||expectedFingerprint!==fresh.previewFingerprint)throw new Error('MCP tool preview fingerprint is stale or does not match the freshly discovered protected tool contract.');const authFetch=await authorizedFetch(fresh.preview.authorizationBinding,fresh.preview.endpoint);const execution=await executeModernMcpToolCall(fresh.preview,fresh.previewFingerprint,{approved:true,expectedFingerprint,fetchImpl:authFetch,cryptoImpl,signal:options.signal});if(!execution.task)return{...execution,attempted:true};const descriptor=await vault.putTask({...execution.task,authorizationBinding:fresh.preview.authorizationBinding,originPreviewFingerprint:fresh.previewFingerprint});return{...sanitizedTaskCreation(execution,descriptor),attempted:true};}
  async function previewMcpResume(tab,endpoint,toolName,args,continuation,inputResponses,binding,options={}){const fresh=await previewMcpTool(tab,endpoint,toolName,args,binding,options);const current={resultType:'input_required',inputRequests:continuation?.inputRequests,requestState:continuation?.requestState??null};const preview={...buildMcpInputRequiredResumePreview(fresh.preview,current,inputResponses,{round:continuation?.round}),authorizationBinding:publicBinding(binding)};const previewFingerprint=await fingerprintMcpToolCallPreview(preview,cryptoImpl);return{ok:true,preview,previewFingerprint};}
  async function executeMcpResume(tab,endpoint,toolName,args,continuation,inputResponses,binding,expectedFingerprint,options={}){if(options.approved!==true)throw new Error('Explicit approval is required before a protected MCP input_required round can resume.');const fresh=await previewMcpResume(tab,endpoint,toolName,args,continuation,inputResponses,binding,options);if(expectedFingerprint!==fresh.previewFingerprint)throw new Error('MCP resume preview fingerprint is stale or does not match.');const authFetch=await authorizedFetch(fresh.preview.authorizationBinding,fresh.preview.endpoint);const execution=await executeModernMcpToolResume(fresh.preview,fresh.previewFingerprint,{approved:true,expectedFingerprint,fetchImpl:authFetch,cryptoImpl,signal:options.signal});if(!execution.task)return{...execution,attempted:true};const descriptor=await vault.putTask({...execution.task,authorizationBinding:fresh.preview.authorizationBinding,originPreviewFingerprint:fresh.previewFingerprint});return{...sanitizedTaskCreation(execution,descriptor),attempted:true};}
  async function listTasks(origin){return vault.listTaskDescriptors(origin);}
  async function refreshTask(tab,endpoint,vaultTaskId,options={}){const stored=await vault.resolveTask(vaultTaskId),target=safeEndpoint(tab,endpoint);if(new URL(stored.endpoint).href!==target.href)throw new Error('Stored MCP task endpoint does not match the authorized tab endpoint.');const authFetch=await authorizedFetch(stored.authorizationBinding,target.href);const updated=await getModernMcpTask(stored,{fetchImpl:authFetch,signal:options.signal,maxResponseBytes:options.maxResponseBytes,timeoutMs:options.timeoutMs});const descriptor=await vault.putTask({...stored,...updated,vaultTaskId,authorizationBinding:stored.authorizationBinding});return publicTaskState(updated,descriptor);}
  async function previewTaskUpdate(tab,endpoint,vaultTaskId,inputResponses,options={}){const stored=await vault.resolveTask(vaultTaskId);safeEndpoint(tab,endpoint);const preview={...buildMcpTaskUpdatePreview(stored,inputResponses,{maxResponseBytes:options.maxResponseBytes,timeoutMs:options.timeoutMs}),authorizationBinding:publicBinding(stored.authorizationBinding)};const previewFingerprint=await fingerprintMcpToolCallPreview(preview,cryptoImpl);return{ok:true,preview,previewFingerprint,vaultTaskId};}
  async function executeTaskUpdate(tab,endpoint,vaultTaskId,inputResponses,expectedFingerprint,options={}){if(options.approved!==true)throw new Error('Explicit approval is required before protected MCP task input can be submitted.');const fresh=await previewTaskUpdate(tab,endpoint,vaultTaskId,inputResponses,options);if(expectedFingerprint!==fresh.previewFingerprint)throw new Error('MCP task update preview fingerprint is stale or does not match.');const stored=await vault.resolveTask(vaultTaskId),authFetch=await authorizedFetch(stored.authorizationBinding,stored.endpoint);const result=await executeModernMcpTaskUpdate(fresh.preview,fresh.previewFingerprint,{approved:true,expectedFingerprint,fetchImpl:authFetch,cryptoImpl,signal:options.signal});return{...result,vaultTaskId};}
  async function previewTaskCancel(tab,endpoint,vaultTaskId,options={}){const stored=await vault.resolveTask(vaultTaskId);safeEndpoint(tab,endpoint);const preview={...buildMcpTaskCancelPreview(stored,{maxResponseBytes:options.maxResponseBytes,timeoutMs:options.timeoutMs}),authorizationBinding:publicBinding(stored.authorizationBinding)};const previewFingerprint=await fingerprintMcpToolCallPreview(preview,cryptoImpl);return{ok:true,preview,previewFingerprint,vaultTaskId};}
  async function executeTaskCancel(tab,endpoint,vaultTaskId,expectedFingerprint,options={}){if(options.approved!==true)throw new Error('Explicit approval is required before a protected MCP task can be cancelled.');const fresh=await previewTaskCancel(tab,endpoint,vaultTaskId,options);if(expectedFingerprint!==fresh.previewFingerprint)throw new Error('MCP task cancel preview fingerprint is stale or does not match.');const stored=await vault.resolveTask(vaultTaskId),authFetch=await authorizedFetch(stored.authorizationBinding,stored.endpoint);const result=await executeModernMcpTaskCancel(fresh.preview,fresh.previewFingerprint,{approved:true,expectedFingerprint,fetchImpl:authFetch,cryptoImpl,signal:options.signal});return{...result,vaultTaskId};}
  function publicCapabilities(){return{storage:'chrome.storage.session',persistent:false,modelVisible:false,cloudVisible:false,protectedMcp:'explicit-session-bearer',backgroundPolling:false,automaticResume:false,maxSecretBytes:sessionVaultLimits.maxSecretBytes,maxTasks:sessionVaultLimits.maxTasks};}
  return{vault,listMcpTools,previewMcpTool,executeMcpTool,previewMcpResume,executeMcpResume,listTasks,refreshTask,previewTaskUpdate,executeTaskUpdate,previewTaskCancel,executeTaskCancel,publicCapabilities};
}
