const ERROR_STATUS={INVALID_ARGUMENTS:400,INVALID_QUERY:400,INVALID_JSON:400,INVALID_TRIGGER:400,INVALID_AUTOMATION_ACTION:400,INVALID_AUTOMATION_ACTIONS:400,INVALID_TOOL_NAME:400,INVALID_PROGRAM:400,STALE_PREVIEW:409,TOOL_NOT_FOUND:404,UNKNOWN_WORK:409,WORK_NOT_SAVED:409,UPSTREAM_RATE_LIMITED:429,UPSTREAM_TIMEOUT:504,UPSTREAM_UNAVAILABLE:502,UPSTREAM_INVALID_RESPONSE:502,TOOL_DEPTH_EXCEEDED:400};
export function method(req,res,allowed){if(!allowed.includes(req.method)){res.setHeader('Allow',allowed.join(', '));res.status(405).json({ok:false,error:{code:'METHOD_NOT_ALLOWED',message:'Method not allowed'}});return false;}return true;}
export function send(res,status,data,headers={}){for(const[k,v]of Object.entries(headers))res.setHeader(k,v);res.setHeader('Content-Type','application/json; charset=utf-8');return res.status(status).json(data);}
export async function readJsonBody(req,maxBytes=131072){
  const declared=Number(req.headers?.['content-length']??req.headers?.['Content-Length']??0); if(Number.isFinite(declared)&&declared>maxBytes){const e=new Error('PAYLOAD_TOO_LARGE');e.status=413;throw e;}
  if(req.body!=null){const raw=typeof req.body==='string'?req.body:JSON.stringify(req.body);if(Buffer.byteLength(raw)>maxBytes){const e=new Error('PAYLOAD_TOO_LARGE');e.status=413;throw e;}if(typeof req.body==='object')return req.body;try{return JSON.parse(raw);}catch{throw new Error('INVALID_JSON');}}
  let raw='';for await(const chunk of req){raw+=chunk;if(Buffer.byteLength(raw)>maxBytes){const e=new Error('PAYLOAD_TOO_LARGE');e.status=413;throw e;}} if(!raw)return{};try{return JSON.parse(raw);}catch{throw new Error('INVALID_JSON');}
}
export function errorResponse(res,error){const code=error?.message||'INTERNAL_ERROR',status=error?.status??ERROR_STATUS[code]??500;const message=status>=500&&!code.startsWith('UPSTREAM_')?'Internal server error':code;return send(res,status,{ok:false,error:{code,message,...(error?.details?{details:error.details}:{})}});}
export function queryParam(req,name){if(req.query&&name in req.query)return Array.isArray(req.query[name])?req.query[name][0]:req.query[name];try{return new URL(req.url??'/', 'https://kata.local').searchParams.get(name);}catch{return null;}}
