import fs from 'node:fs';import path from 'node:path';import {createHash} from 'node:crypto';import {execFileSync} from 'node:child_process';
const root=path.resolve(new URL('..',import.meta.url).pathname);const walk=d=>fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(d,e.name)):[path.join(d,e.name)]);const js=walk(root).filter(f=>f.endsWith('.js')&&!f.includes('/dist/'));
for(const file of js)execFileSync(process.execPath,['--check',file],{stdio:'pipe'});
const source=js.map(f=>fs.readFileSync(f,'utf8')).join('\n');for(const bad of [/\beval\s*\(/,/new\s+Function\s*\(/,/\burl\.parse\s*\(/])if(bad.test(source))throw new Error(`Forbidden source pattern: ${bad}`);
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');if(/\son[a-z]+\s*=/i.test(html)||/\sstyle\s*=/i.test(html))throw new Error('Inline handlers/styles violate CSP');
const config=JSON.parse(fs.readFileSync(path.join(root,'vercel.json'),'utf8'));const headers=config.headers?.[0]?.headers??[];const csp=headers.find(x=>x.key==='Content-Security-Policy')?.value??'';if(!csp.includes("script-src 'self'")||csp.includes('unsafe-inline')||csp.includes('unsafe-eval')||!csp.includes("frame-ancestors 'none'"))throw new Error('CSP release contract failed');
const expected=['/dashboard','/research','/automations','/teach','/tools','/developers','/activity','/learn','/settings'];const rewrites=new Set(config.rewrites.map(x=>x.source));for(const r of expected)if(!rewrites.has(r))throw new Error(`Missing product rewrite ${r}`);
const manifest=JSON.parse(fs.readFileSync(path.join(root,'dist/integrity.json'),'utf8'));for(const [rel,meta] of Object.entries(manifest.assets)){const b=fs.readFileSync(path.join(root,'dist',rel.slice(1)));const sha=createHash('sha256').update(b).digest('hex');if(sha!==meta.sha256)throw new Error(`Integrity mismatch ${rel}`);}
console.log(`Static/security check passed: ${js.length} JS modules, ${expected.length+1} product routes, ${Object.keys(manifest.assets).length} integrity assets.`);
