import {createWebMcpRegistry} from './webmcp.js';
const STORAGE='kata.v3.local';
const routes=[['Dashboard','/dashboard'],['Research','/research'],['Automations','/automations'],['Teach','/teach'],['Tools','/tools'],['Developers','/developers'],['Activity','/activity'],['Learn','/learn'],['Settings','/settings']];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clone=v=>structuredClone(v);const now=()=>new Date().toISOString();
const emptyWorkspace=()=>({version:1,knownWorks:{},savedWorks:{},runs:{},activity:[]});
function defaultState(){return{workspace:emptyWorkspace(),results:[],automations:[],programs:[],activity:[],demos:{A:[],B:[]},recording:null,lastQuery:'web agents'};}
function load(){try{const x=JSON.parse(localStorage.getItem(STORAGE));if(x&&x.workspace?.version===1&&Array.isArray(x.automations)&&Array.isArray(x.programs))return{...defaultState(),...x};}catch{}return defaultState();}
function safeLink(value){try{const u=new URL(value);return u.protocol==='https:'||u.protocol==='http:'?u.href:null;}catch{return null;}}
function human(code){return({INVALID_ARGUMENTS:'Check the fields and try again.',INVALID_QUERY:'Enter a search query.',UPSTREAM_TIMEOUT:'OpenAlex timed out. Retry the search.',UPSTREAM_RATE_LIMITED:'OpenAlex is rate limiting requests. Retry shortly.',UPSTREAM_UNAVAILABLE:'OpenAlex is temporarily unavailable.',STALE_PREVIEW:'This automation changed after preview. Preview it again before running.',UNKNOWN_WORK:'That work is not loaded anymore.',WORK_NOT_SAVED:'Save the work before changing it.',DEMO_STRUCTURE_MISMATCH:'The two demonstrations use different action structures.',TOOL_DEPTH_EXCEEDED:'Nested tool execution exceeded KATA’s safety limit.'}[code]??code??'Unexpected error');}
async function request(path,{method='GET',body,signal}={}){signal?.throwIfAborted();const r=await fetch(path,{method,headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined,signal});let data;try{data=await r.json();}catch(error){if(signal?.aborted)throw signal.reason??error;throw new Error(`HTTP_${r.status}`);}signal?.throwIfAborted();if(!r.ok||data.ok===false){const e=new Error(data?.error?.code??`HTTP_${r.status}`);e.details=data?.error?.details;throw e;}return data;}

export function createApp(root){
  if(!root)throw new Error('APP_ROOT_MISSING');let state=load(),route=location.pathname,health=null,webmcp={supported:false,active:[],error:null};let automationDraft=null,automationPreview=null,developerOutput='Choose a tool and send a real request.';let disposed=false;
  const persist=()=>localStorage.setItem(STORAGE,JSON.stringify(state));
  const activity=(message,source='human',type='info',meta={})=>{state.activity.unshift({message,source,type,meta,at:now()});state.activity=state.activity.slice(0,100);persist();};
  const summary=()=>({knownWorks:Object.keys(state.workspace.knownWorks).length,savedWorks:Object.keys(state.workspace.savedWorks).length,automations:state.automations.length,learnedTools:state.programs.map(p=>p.name),recording:state.recording});
  async function invoke(name,args,{signal}={}){const data=await request('/api/invoke',{method:'POST',body:{name,arguments:args},signal});signal?.throwIfAborted();return data.result;}
  async function apply(command,source='human'){
    const out=await invoke('kata_apply_command',{workspace:state.workspace,command});state.workspace=out.workspace;if(source==='human'&&state.recording){state.demos[state.recording].push(clone(command));activity(`${command.kind} recorded in Demo ${state.recording}.`,'human','command',{command});}else activity(`${command.kind} completed.`,source,'command',{command});persist();render();return out;
  }
  async function search(query=state.lastQuery,limit=8,source='human',{signal}={}){
    const before=signal?clone(state):null;
    try{
      const data=await request(`/api/search?query=${encodeURIComponent(query)}&limit=${Math.max(1,Math.min(25,limit))}`,{signal});signal?.throwIfAborted();state.lastQuery=query;state.results=data.works;for(const w of data.works)state.workspace.knownWorks[w.id]=w;activity(`Loaded ${data.works.length} live OpenAlex works for “${query}”.`,source,'search');persist();render();await runTrigger('AFTER_SEARCH',data.works,{signal});signal?.throwIfAborted();return data;
    }catch(error){if(signal?.aborted&&before){state=before;persist();render();}throw error;}
  }
  function candidates(){return state.results.length?state.results:Object.values(state.workspace.knownWorks);}
  async function previewAutomation(automation,works=candidates(),{signal}={}){return invoke('kata_preview_automation',{workspace:state.workspace,works,automation},{signal});}
  async function runAutomation(id,source='human',works=candidates(),{signal}={}){
    signal?.throwIfAborted();const stored=state.automations.find(a=>a.id===id);if(!stored)throw new Error('AUTOMATION_NOT_FOUND');const p=await previewAutomation(stored,works,{signal});signal?.throwIfAborted();const out=await invoke('kata_run_automation',{workspace:state.workspace,works,automation:stored,previewFingerprint:p.preview.fingerprint},{signal});signal?.throwIfAborted();state.workspace=out.workspace;activity(`${stored.name}: ${out.receipt.status}, ${out.receipt.processed??0} processed.`,source,'automation',out.receipt);persist();render();return out.receipt;
  }
  async function runTrigger(trigger,works,{signal}={}){signal?.throwIfAborted();for(const a of state.automations.filter(x=>x.enabled&&x.trigger===trigger)){try{await runAutomation(a.id,'automation',works,{signal});}catch(error){if(signal?.aborted)throw signal.reason??error;activity(`${a.name}: ${human(error.message)}`,'automation','error',{code:error.message});}}signal?.throwIfAborted();render();}
  async function executeProgram(name,input,source='human',{signal}={}){
    signal?.throwIfAborted();const p=state.programs.find(x=>x.name===name);if(!p)throw new Error('TOOL_NOT_FOUND');const data=await request('/api/execute',{method:'POST',body:{workspace:state.workspace,program:p,input},signal});signal?.throwIfAborted();state.workspace=data.workspace;activity(`${name} executed ${data.completed} semantic action(s).`,source,'tool');persist();render();return{completed:data.completed,workspaceSummary:summary()};
  }
  const registry=createWebMcpRegistry({getWorkspace:()=>state.workspace,setWorkspace:x=>{state.workspace=x;persist();render();},search,summary,listAutomations:()=>clone(state.automations),runAutomation,listPrograms:()=>clone(state.programs),executeProgram},s=>{webmcp=s;if(!disposed)render();});
  function navigate(path){history.pushState({},'',path);route=path;window.scrollTo({top:0,behavior:'auto'});render();}
  const nav=()=>`<aside class="rail"><a class="brand" data-nav href="/"><span>K</span><div><strong>KATA</strong><small>AGENT AUTOMATION</small></div></a><nav>${routes.map(([n,p],i)=>`<a data-nav href="${p}" class="${route===p?'active':''}"><em>${String(i+1).padStart(2,'0')}</em>${n}</a>`).join('')}</nav><div class="rail-status"><span><i class="${health?.ok?'ok':''}"></i>API ${health?.ok?'online':'checking'}</span><span><i class="${webmcp.supported&&!webmcp.error?'ok':''}"></i>WebMCP ${webmcp.supported?(webmcp.error?'error':'live'):'compat'}</span></div></aside>`;
  const head=(k,t,d,a='')=>`<header class="page-head"><div><p class="eyebrow">${esc(k)}</p><h1>${esc(t)}</h1><p>${esc(d)}</p></div>${a?`<div class="head-actions">${a}</div>`:''}</header>`;
  function landing(){return`<div class="landing"><header class="landing-nav"><a data-nav href="/" class="wordmark">KATA</a><nav><a data-nav href="/developers">Developers</a><a data-nav href="/learn">Docs</a><button data-go="/dashboard" class="primary">Open KATA</button></nav></header><main><section class="hero"><p class="eyebrow signal">DETERMINISTIC AGENT INFRASTRUCTURE</p><h1>Teach workflows once.<br><em>Expose them everywhere.</em></h1><p>KATA turns semantic application actions into reusable automations and typed tools across HTTP, MCP 2026-07-28, WebMCP, OpenAI-style functions and Anthropic-style tools.</p><div class="hero-actions"><button data-go="/research" class="primary big">Use live research</button><button data-go="/developers" class="big">Connect an agent</button></div><div class="protocol-row"><article><b>HTTP</b><span>/api/invoke</span></article><article><b>MCP</b><span>/api/mcp</span></article><article><b>WebMCP</b><span>document.modelContext</span></article><article><b>Agent schemas</b><span>/api/agents</span></article></div></section><section class="landing-grid"><article><span>01</span><h2>Real data</h2><p>Searches go through KATA’s live OpenAlex connector. Failures stay failures—there is no synthetic research fallback.</p></article><article><span>02</span><h2>Semantic execution</h2><p>Automations operate on typed commands and are preview-bound, transactional and depth-limited.</p></article><article><span>03</span><h2>One engine</h2><p>Human UI, server API, remote MCP and browser WebMCP converge on the same tool contracts.</p></article></section></main></div>`;}
  function dashboard(){const s=summary();return`<section class="page">${head('COMMAND CENTER','KATA workspace','Start from an outcome, then use the same capability from a person, script or agent.')}<div class="goal-grid"><button data-go="/research"><strong>Research with live data</strong><span>Search OpenAlex and build a validated workspace.</span></button><button data-go="/automations"><strong>Automate triage</strong><span>Preview exact matches before enabling actions.</span></button><button data-go="/teach"><strong>Teach a tool</strong><span>Record the same semantic routine twice.</span></button><button data-go="/developers"><strong>Connect an agent</strong><span>HTTP, MCP, WebMCP, OpenAI and Anthropic schemas.</span></button></div><div class="metrics"><article><strong>${s.knownWorks}</strong><span>known works</span></article><article><strong>${s.savedWorks}</strong><span>saved</span></article><article><strong>${s.automations}</strong><span>automations</span></article><article><strong>${s.learnedTools.length}</strong><span>learned tools</span></article></div>${state.recording?`<div class="callout warn"><b>Recording Demo ${state.recording}</b><span>Research actions are being captured as semantic commands.</span><button data-stop-recording>Stop recording</button></div>`:''}<section class="section"><div class="section-bar"><h2>System status</h2></div><div class="status-grid"><article><span>HTTP API</span><b>${health?.ok?'Online':'Checking'}</b></article><article><span>WebMCP</span><b>${webmcp.supported?(webmcp.error?'Registration error':`${webmcp.active.length} tools live`):'Browser compatibility mode'}</b></article><article><span>Research source</span><b>OpenAlex live connector</b></article><article><span>Execution boundary</span><b>Browser-owned workspace</b></article></div></section></section>`;}
  function research(){return`<section class="page">${head('LIVE CONNECTOR','Research','Search real OpenAlex works. All saved-state mutations execute through KATA’s canonical semantic tool API.')}<form data-form="search" class="search"><input name="query" value="${esc(state.lastQuery)}" maxlength="240" required><select name="limit"><option>8</option><option>15</option><option>25</option></select><button class="primary">Search</button></form>${state.recording?`<div class="record-banner"><b>Recording Demo ${state.recording}</b><span>Save, prioritize or tag a work; KATA records the semantic action, not the click.</span><button type="button" data-stop-recording>Finish demo</button></div>`:''}<div class="research-layout"><section><div class="section-bar"><h2>Results</h2><span>${state.results.length}</span></div>${state.results.length?`<div class="work-list">${state.results.map(workCard).join('')}</div>`:`<div class="empty"><h3>No cached demo results.</h3><p>Run a live search to begin.</p></div>`}</section><aside><div class="section-bar"><h2>Workspace</h2><span>${Object.keys(state.workspace.savedWorks).length}</span></div><div class="saved-list">${Object.values(state.workspace.savedWorks).length?Object.values(state.workspace.savedWorks).map(savedCard).join(''):`<div class="empty compact"><p>Saved works appear here.</p></div>`}</div></aside></div></section>`;}
  function workCard(w){const saved=state.workspace.savedWorks[w.id],link=safeLink(w.url);return`<article class="work"><div class="work-meta"><span>${esc(w.year??'—')}</span><span>${esc(w.citations??0)} citations</span></div><h3>${esc(w.title)}</h3><p>${esc((w.authors??[]).join(', ')||'Authors unavailable')}</p>${link?`<a href="${esc(link)}" target="_blank" rel="noreferrer">Source ↗</a>`:''}<div class="work-actions">${saved?`<span class="pill live">SAVED</span><button data-command="SET_PRIORITY" data-work="${esc(w.id)}" data-value="high">High priority</button>`:`<button class="primary" data-command="SAVE_WORK" data-work="${esc(w.id)}">Save</button>`}</div></article>`;}
  function savedCard(w){return`<article class="saved"><h3>${esc(w.title)}</h3><div class="saved-controls"><select data-priority="${esc(w.id)}"><option ${w.priority==='low'?'selected':''}>low</option><option ${w.priority==='medium'?'selected':''}>medium</option><option ${w.priority==='high'?'selected':''}>high</option></select><form data-form="tag" data-work="${esc(w.id)}"><input name="tag" maxlength="80" placeholder="Add tag"><button>Add</button></form></div><textarea data-note="${esc(w.id)}" maxlength="4000" rows="2" placeholder="Note">${esc(w.note)}</textarea><div class="tags">${(w.tags??[]).map(t=>`<span class="pill">${esc(t)}</span>`).join('')}</div></article>`;}
  function automations(){return`<section class="page">${head('SAFE EXECUTION','Automations','Automations are explicit When → Match → Do contracts. Activation requires an exact current preview fingerprint.')}<div class="builder"><form data-form="automation" class="form-grid"><label>Name<input name="name" value="Recent high-signal research" maxlength="120" required></label><label>Trigger<select name="trigger"><option value="AFTER_SEARCH">After search</option><option value="WORKSPACE_OPEN">Workspace open</option><option value="MANUAL">Manual / agent</option></select></label><label>Minimum year<input name="minYear" type="number" min="1900" max="2100" value="2024"></label><label>Minimum citations<input name="minCitations" type="number" min="0" value="50"></label><label>Priority<select name="priority"><option value="none">No change</option><option>low</option><option>medium</option><option selected>high</option></select></label><label>Tag<input name="tag" value="review" maxlength="80"></label><label>Max items<input name="maxItems" type="number" min="1" max="25" value="5"></label><label class="check"><input name="onlyUnsaved" type="checkbox" checked>Only unsaved works</label><button class="primary wide">Preview exact effects</button></form>${automationPreview&&automationDraft?`<div class="preview-panel"><p class="eyebrow signal">PREVIEW — NO CHANGES APPLIED</p><h2>${automationPreview.matches.length} matching work(s)</h2><p>${automationPreview.plannedOperations} semantic operations planned.</p><code>${esc(automationPreview.fingerprint.slice(0,20))}…</code><button data-enable-automation class="primary">Enable this exact rule</button></div>`:''}</div><section class="section"><div class="section-bar"><h2>Configured automations</h2><span>${state.automations.length}</span></div>${state.automations.length?`<div class="automation-list">${state.automations.map(a=>`<article><div><span class="pill ${a.enabled?'live':''}">${a.enabled?'ACTIVE':'PAUSED'}</span><h3>${esc(a.name)}</h3><p>${esc(a.trigger.replaceAll('_',' '))} · max ${a.maxItemsPerRun}</p></div><div><button data-run-auto="${esc(a.id)}">Run now</button><button data-toggle-auto="${esc(a.id)}">${a.enabled?'Pause':'Resume'}</button></div></article>`).join('')}</div>`:`<div class="empty"><h3>No rules yet.</h3><p>Load live research first if you want a meaningful preview.</p></div>`}</section></section>`;}
  function trace(slot){const d=state.demos[slot];return d.length?`<ol class="trace">${d.map((x,i)=>`<li><span>${i+1}</span><b>${esc(x.kind)}</b><code>${esc(JSON.stringify(x.args))}</code></li>`).join('')}</ol>`:`<div class="empty compact"><p>No actions captured.</p></div>`;}
  function teach(){return`<section class="page">${head('PROGRAMMING BY DEMONSTRATION','Teach a tool','Record the same semantic workflow on two different works. KATA anti-unifies values into typed parameters; it never generates arbitrary code.')}<div class="teach-grid"><article><div class="section-bar"><h2>Demo A</h2><button data-record="A" class="${state.recording==='A'?'primary':''}">${state.recording==='A'?'Recording…':'Record A'}</button></div>${trace('A')}</article><article><div class="section-bar"><h2>Demo B</h2><button data-record="B" class="${state.recording==='B'?'primary':''}">${state.recording==='B'?'Recording…':'Record B'}</button></div>${trace('B')}</article></div>${state.recording?`<div class="callout warn"><b>Demo ${state.recording} is active.</b><span>Go to Research and perform the semantic actions you want to teach.</span><button data-stop-recording>Finish demo</button></div>`:''}${state.demos.A.length&&state.demos.B.length?`<form data-form="compile" class="compile"><label>Tool name<input name="name" value="triage_research" pattern="[A-Za-z0-9_. -]{1,128}" required></label><button class="primary">Compile & install</button></form>`:''}<section class="section"><div class="section-bar"><h2>Installed learned tools</h2><span>${state.programs.length}</span></div>${state.programs.length?state.programs.map(p=>`<article class="program"><h3><code>${esc(p.name)}</code></h3><p>${esc(p.description)}</p><pre>${esc(JSON.stringify(p.inputSchema,null,2))}</pre></article>`).join(''):`<div class="empty"><p>No learned programs installed.</p></div>`}</section></section>`;}
  function tools(){return`<section class="page">${head('AGENT SURFACE','Tools','Browser-native WebMCP tools are registered from current state. Learned tools appear dynamically after compilation.')}<div class="connection ${webmcp.supported&&!webmcp.error?'good':''}"><div><p class="eyebrow">WEBMCP</p><h2>${webmcp.supported?(webmcp.error?'Registration error':`${webmcp.active.length} tools registered`):'Compatibility mode'}</h2><p>${webmcp.supported?'Using document.modelContext with abortable registrations.':'This browser does not expose document.modelContext. HTTP and MCP still work.'}</p></div><button data-refresh-webmcp>Refresh</button></div><section class="section"><div class="section-bar"><h2>Active browser tools</h2></div><div class="tool-grid">${(webmcp.active.length?webmcp.active:['kata_search_research','kata_workspace_summary','kata_list_automations','kata_run_automation','kata_list_learned_tools']).map(n=>`<article><span class="pill">${state.programs.some(p=>p.name===n)?'LEARNED':'BUILT IN'}</span><h3><code>${esc(n)}</code></h3></article>`).join('')}</div></section></section>`;}
  function developers(){return`<section class="page">${head('PROTOCOL CONTROL PLANE','Developers','Use the protocol your agent already speaks. All bridges derive from the same canonical tool registry.')}<div class="protocol-cards"><article><span>MCP 2026-07-28</span><h2>POST /api/mcp</h2><p>Stateless JSON-RPC with MCP-Protocol-Version, Mcp-Method and Mcp-Name routing headers.</p></article><article><span>Generic HTTP</span><h2>POST /api/invoke</h2><p>Invoke any canonical tool with <code>{ name, arguments }</code>.</p></article><article><span>WebMCP</span><h2>document.modelContext</h2><p>Stateful browser tools operate on the same visible local workspace.</p></article><article><span>Framework bridges</span><h2>GET /api/agents</h2><p>OpenAI function and Anthropic tool definitions generated from canonical schemas.</p></article></div><section class="section"><div class="section-bar"><h2>Live API console</h2><a href="/api/openapi" target="_blank" rel="noreferrer">OpenAPI ↗</a></div><form data-form="developer" class="developer-console"><label>Tool<select name="tool"><option>kata_search_research</option><option>kata_plan_triage</option><option>kata_compile_workflow</option></select></label><label>Arguments<textarea name="args" rows="9">${esc(JSON.stringify({query:'web agents',limit:3},null,2))}</textarea></label><button class="primary">Invoke real tool</button><pre>${esc(developerOutput)}</pre></form></section><section class="section"><h2>MCP request example</h2><pre>POST /api/mcp\nContent-Type: application/json\nAccept: application/json, text/event-stream\nMCP-Protocol-Version: 2026-07-28\nMcp-Method: tools/call\nMcp-Name: kata_search_research\n\n{"jsonrpc":"2.0","id":1,"method":"tools/call","params":{"name":"kata_search_research","arguments":{"query":"web agents","limit":3},"_meta":{"io.modelcontextprotocol/protocolVersion":"2026-07-28","io.modelcontextprotocol/clientCapabilities":{},"io.modelcontextprotocol/clientInfo":{"name":"kata-developer-console","version":"1.0"}}}}</pre></section></section>`;}
  function activityPage(){const entries=[...state.activity,...(state.workspace.activity??[])].sort((a,b)=>String(b.at).localeCompare(String(a.at))).slice(0,100);return`<section class="page">${head('AUDITABILITY','Activity','Human actions, agent calls, automation receipts and recoverable failures remain inspectable.')}<div class="activity-list">${entries.length?entries.map(e=>`<article class="${e.type==='error'?'bad':''}"><div><span class="pill">${esc(e.source??e.type??'system')}</span><time>${esc(new Date(e.at).toLocaleString())}</time></div><p>${esc(e.message)}</p></article>`).join(''):`<div class="empty"><p>No activity yet.</p></div>`}</div></section>`;}
  function learn(){return`<section class="page docs">${head('OPERATIONS','Learn KATA','The shortest path from live data to a reusable agent capability.')}<article><h2>1. Load real candidates</h2><p>Research queries go to KATA’s OpenAlex connector. Results are normalized and loaded into the browser-owned workspace.</p></article><article><h2>2. Build a safe automation</h2><p>Automations have explicit triggers, filters and allowlisted actions. Every activation requires a preview fingerprint bound to the current rule, candidates and saved-state boundary.</p></article><article><h2>3. Teach a new tool</h2><p>Record Demo A, repeat the same semantic actions on a different work as Demo B, then compile. Equal values remain literals; differing primitive values become JSON-Schema parameters.</p></article><article><h2>4. Connect agents</h2><p>Use browser WebMCP for the live page state, remote MCP for standardized agent clients, /api/invoke for generic HTTPS, or /api/agents for OpenAI/Anthropic tool schemas.</p></article><article><h2>Boundary</h2><p>Browser-local AFTER_SEARCH and WORKSPACE_OPEN triggers execute while KATA is open. KATA does not falsely claim unattended cloud scheduling without a durable authenticated runner.</p></article></section>`;}
  function settings(){return`<section class="page">${head('CONTROL PLANE','Settings','Connectivity, local data and recovery controls.')}<div class="settings-grid"><article><span>HTTP API</span><h2>${health?.ok?'Online':'Unavailable'}</h2><button data-health>Recheck</button></article><article><span>WebMCP</span><h2>${webmcp.supported?(webmcp.error?'Error':'Connected'):'Compatibility'}</h2><button data-refresh-webmcp>Re-register</button></article><article><span>Local workspace</span><h2>${Object.keys(state.workspace.savedWorks).length} saved works</h2><button data-export>Export JSON</button></article><article><span>Reset</span><h2>Clear browser state</h2><button data-reset class="danger">Reset KATA</button></article></div></section>`;}
  function notFound(){return`<section class="page">${head('404','Page not found','This route is not part of KATA.')}<button class="primary" data-go="/dashboard">Go to dashboard</button></section>`;}
  function shell(content){return`<div class="shell">${nav()}<main class="stage">${state.recording?`<div class="global-record"><span>REC Demo ${state.recording}</span><button data-stop-recording>Stop</button></div>`:''}${content}</main></div>`;}
  function render(){if(disposed)return;const page=route==='/'?landing():route==='/dashboard'?dashboard():route==='/research'?research():route==='/automations'?automations():route==='/teach'?teach():route==='/tools'?tools():route==='/developers'?developers():route==='/activity'?activityPage():route==='/learn'?learn():route==='/settings'?settings():notFound();root.innerHTML=route==='/'?page:shell(page);}
  function automationFromForm(form){const d=new FormData(form),actions=[{kind:'SAVE_WORK'}];if(d.get('priority')!=='none')actions.push({kind:'SET_PRIORITY',value:String(d.get('priority'))});const tag=String(d.get('tag')??'').trim();if(tag)actions.push({kind:'ADD_TAG',value:tag});return{name:String(d.get('name')),trigger:String(d.get('trigger')),filters:{minYear:d.get('minYear')?Number(d.get('minYear')):null,minCitations:d.get('minCitations')?Number(d.get('minCitations')):null,onlyUnsaved:d.get('onlyUnsaved')==='on'},actions,maxItemsPerRun:Number(d.get('maxItems')||5),enabled:true};}
  root.addEventListener('click',async event=>{const el=event.target.closest?.('a,button,[data-command]');if(!el)return;try{
    if(el.matches('a[data-nav]')){event.preventDefault();navigate(el.getAttribute('href'));return;}if(el.dataset.go){navigate(el.dataset.go);return;}if(el.dataset.command){await apply({kind:el.dataset.command,args:{workId:el.dataset.work,...(el.dataset.command==='SET_PRIORITY'?{priority:el.dataset.value}:{})}});return;}
    if(el.dataset.record){state.recording=el.dataset.record;state.demos[state.recording]=[];persist();navigate('/research');return;}if(el.hasAttribute('data-stop-recording')){const slot=state.recording;state.recording=null;activity(`Demo ${slot} recording stopped.`);persist();render();return;}
    if(el.hasAttribute('data-enable-automation')){if(!automationDraft||!automationPreview)throw new Error('STALE_PREVIEW');state.automations.push({...automationDraft,previewFingerprint:automationPreview.fingerprint});automationDraft=null;automationPreview=null;activity('Automation enabled.','human','automation');persist();render();return;}
    if(el.dataset.runAuto){await runAutomation(el.dataset.runAuto);return;}if(el.dataset.toggleAuto){const a=state.automations.find(x=>x.id===el.dataset.toggleAuto);if(a){a.enabled=!a.enabled;a.status=a.enabled?'active':'paused';persist();render();}return;}
    if(el.hasAttribute('data-refresh-webmcp')){await registry.refresh();return;}if(el.hasAttribute('data-health')){await refreshHealth();return;}if(el.hasAttribute('data-export')){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='kata-workspace.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),0);return;}if(el.hasAttribute('data-reset')){localStorage.removeItem(STORAGE);state=defaultState();automationDraft=null;automationPreview=null;persist();await registry.refresh();render();return;}
  }catch(error){activity(human(error.message),'human','error',{code:error.message});render();}});
  root.addEventListener('change',async event=>{const el=event.target;try{if(el.matches('[data-priority]'))await apply({kind:'SET_PRIORITY',args:{workId:el.dataset.priority,priority:el.value}});else if(el.matches('[data-note]'))await apply({kind:'SET_NOTE',args:{workId:el.dataset.note,note:el.value}});}catch(error){activity(human(error.message),'human','error');render();}});
  root.addEventListener('input',event=>{if(event.target.closest?.('form[data-form="automation"]')){automationDraft=null;automationPreview=null;root.querySelector('.preview-panel')?.remove();}});
  root.addEventListener('submit',async event=>{const form=event.target;if(!(form instanceof HTMLFormElement)||!form.dataset.form)return;event.preventDefault();try{
    if(form.dataset.form==='search'){const d=new FormData(form);await search(String(d.get('query')),Number(d.get('limit')||8));}
    else if(form.dataset.form==='tag'){const tag=String(new FormData(form).get('tag')??'').trim();if(tag)await apply({kind:'ADD_TAG',args:{workId:form.dataset.work,tag}});}
    else if(form.dataset.form==='automation'){const definition=automationFromForm(form),out=await previewAutomation(definition);automationDraft=out.automation;automationPreview=out.preview;render();}
    else if(form.dataset.form==='compile'){const name=String(new FormData(form).get('name'));const data=await request('/api/compile',{method:'POST',body:{name,demos:[state.demos.A,state.demos.B]}});if(state.programs.some(p=>p.name===data.program.name))throw new Error('DUPLICATE_TOOL_NAME');state.programs.push(data.program);state.demos={A:[],B:[]};activity(`${data.program.name} compiled and installed.`,'human','tool');persist();await registry.refresh();navigate('/tools');}
    else if(form.dataset.form==='developer'){const d=new FormData(form);let args;try{args=JSON.parse(String(d.get('args')));}catch{throw new Error('INVALID_JSON');}const data=await request('/api/invoke',{method:'POST',body:{name:String(d.get('tool')),arguments:args}});developerOutput=JSON.stringify(data.result,null,2);render();}
  }catch(error){activity(human(error.message),'human','error',{code:error.message});developerOutput=JSON.stringify({ok:false,error:error.message,details:error.details??null},null,2);render();}});
  async function refreshHealth(){try{health=await request('/api/health');}catch(error){health={ok:false,error:error.message};}render();}
  const pop=()=>{route=location.pathname;render();};window.addEventListener('popstate',pop);render();refreshHealth();registry.refresh();queueMicrotask(()=>runTrigger('WORKSPACE_OPEN',Object.values(state.workspace.knownWorks)));
  return{dispose(){disposed=true;window.removeEventListener('popstate',pop);registry.dispose();},navigate};
}
