import {assertSchema} from '../lib/shared/schema.js';

const MCP_VERSION='2026-07-28';
const TOOL_NAME=/^[A-Za-z0-9_.-]{1,128}$/;
const TCHAR=/^[!#$%&'*+\-.^_`|~0-9A-Za-z]+$/;
const INPUT_SCHEMA_KEYS=new Set(['$schema','type','enum','properties','required','additionalProperties','items','minItems','maxItems','minLength','maxLength','pattern','minimum','maximum','title','description','default','examples','example','format','deprecated','readOnly','writeOnly','x-mcp-header']);
const MAX_RESPONSE_BYTES=1024*1024;

function safeEndpoint(raw){try{const url=new URL(String(raw));if(!['http:','https:'].includes(url.protocol)||url.username||url.password)throw new Error();url.hash='';return url;}catch{throw new TypeError('A safe HTTP(S) MCP endpoint is required.');}}
function boundedInt(value,fallback,min,max){const n=Number(value);return Number.isInteger(n)?Math.max(min,Math.min(max,n)):fallback;}
function canonicalize(value){if(value===null||typeof value==='string'||typeof value==='boolean')return value;if(typeof value==='number'){if(!Number.isFinite(value))throw new TypeError('MCP preview contains a non-finite number.');return value;}if(Array.isArray(value))return value.map(canonicalize);if(value&&typeof value==='object'){const out={};for(const key of Object.keys(value).sort())out[key]=canonicalize(value[key]);return out;}throw new TypeError('MCP preview contains a non-JSON value.');}
function schemaError(schema,path='$'){if(!schema||typeof schema!=='object'||Array.isArray(schema))return `inputSchema is not a JSON Schema object at ${path}`;for(const key of Object.keys(schema))if(!INPUT_SCHEMA_KEYS.has(key))return `unsupported executable JSON Schema keyword ${key} at ${path}`;if(Array.isArray(schema.type))return `union types are not executable at ${path}`;if(schema.additionalProperties!==undefined&&typeof schema.additionalProperties!=='boolean')return `schema-valued additionalProperties is not executable at ${path}`;if(schema.properties!==undefined){if(!schema.properties||typeof schema.properties!=='object'||Array.isArray(schema.properties))return `invalid properties at ${path}`;for(const [name,child] of Object.entries(schema.properties)){const error=schemaError(child,`${path}.properties.${name}`);if(error)return error;}}if(schema.items!==undefined){const error=schemaError(schema.items,`${path}.items`);if(error)return error;}return null;}
function collectHeaderMappings(schema,path=[],seen=new Map(),out=[]){for(const [name,child] of Object.entries(schema?.properties??{})){const next=[...path,name],header=child?.['x-mcp-header'];if(header!==undefined){if(typeof header!=='string'||!header||!TCHAR.test(header))throw new TypeError(`Invalid x-mcp-header on ${next.join('.')}`);if(!['string','integer','boolean'].includes(child?.type))throw new TypeError(`x-mcp-header requires string, integer, or boolean at ${next.join('.')}`);const lower=header.toLowerCase();if(seen.has(lower))throw new TypeError(`Duplicate x-mcp-header value: ${header}`);seen.set(lower,true);out.push({path:next,header,type:child.type});}if(child?.type==='object')collectHeaderMappings(child,next,seen,out);}return out;}
function getPath(value,path){let current=value;for(const part of path){if(current===null||typeof current!=='object'||!(part in current))return undefined;current=current[part];}return current;}
function headerValue(value,type,path){if(type==='integer'){if(!Number.isSafeInteger(value))throw new TypeError(`MCP mirrored integer is outside the safe range at ${path.join('.')}`);return String(value);}if(type==='boolean'){if(typeof value!=='boolean')throw new TypeError(`MCP mirrored boolean is invalid at ${path.join('.')}`);return value?'true':'false';}if(typeof value!=='string')throw new TypeError(`MCP mirrored string is invalid at ${path.join('.')}`);if(/[\r\n]/.test(value))throw new TypeError(`MCP mirrored header value contains a line break at ${path.join('.')}`);return value;}
function meta(){return{'io.modelcontextprotocol/protocolVersion':MCP_VERSION,'io.modelcontextprotocol/clientCapabilities':{},'io.modelcontextprotocol/clientInfo':{name:'kata-interop-adapter',version:'3.0.0'}};}
function requestBody(id,method,params={}){return{jsonrpc:'2.0',id,method,params:{...params,_meta:meta()}};}
function requestHeaders(method,extra={}){return{'Content-Type':'application/json','Accept':'application/json, text/event-stream','MCP-Protocol-Version':MCP_VERSION,'Mcp-Method':method,...extra};}
async function readSseJsonRpc(response,id,maxBytes){const text=await boundedText(response,maxBytes);let data=[];for(const line of text.split(/\r?\n/)){if(line.startsWith(':'))continue;if(line.startsWith('data:'))data.push(line.slice(5).trimStart());else if(line===''){if(data.length){const raw=data.join('\n');data=[];try{const value=JSON.parse(raw);if(value?.id===id)return value;}catch{}}}}if(data.length){try{const value=JSON.parse(data.join('\n'));if(value?.id===id)return value;}catch{}}throw new Error('MCP SSE response ended without the final JSON-RPC response.');}
async function boundedText(response,maxBytes){if(response?.body?.getReader){const reader=response.body.getReader(),chunks=[];let total=0;try{while(true){const {done,value}=await reader.read();if(done)break;const chunk=value instanceof Uint8Array?value:new Uint8Array(value??[]);if(total+chunk.length>maxBytes){await reader.cancel?.();throw new Error('MCP response exceeded the bounded response limit.');}chunks.push(chunk);total+=chunk.length;}}finally{try{reader.releaseLock?.();}catch{}}const merged=new Uint8Array(total);let offset=0;for(const chunk of chunks){merged.set(chunk,offset);offset+=chunk.length;}return new TextDecoder().decode(merged);}if(typeof response?.text==='function'){const text=await response.text();if(new TextEncoder().encode(text).length>maxBytes)throw new Error('MCP response exceeded the bounded response limit.');return text;}throw new Error('MCP response body is unavailable.');}
async function readJsonRpc(response,id,maxBytes=MAX_RESPONSE_BYTES){const type=String(response?.headers?.get?.('content-type')??'').toLowerCase();if(type.includes('text/event-stream'))return readSseJsonRpc(response,id,maxBytes);if(typeof response?.json==='function')return response.json();const text=await boundedText(response,maxBytes);return JSON.parse(text);}
async function post(endpoint,method,params,options={}){const fetchImpl=options.fetchImpl??globalThis.fetch;if(typeof fetchImpl!=='function')throw new Error('fetch is unavailable.');const id=options.id??`kata-${method.replace('/','-')}`;const maxResponseBytes=boundedInt(options.maxResponseBytes,MAX_RESPONSE_BYTES,1,MAX_RESPONSE_BYTES);const response=await fetchImpl(safeEndpoint(endpoint).href,{method:'POST',headers:requestHeaders(method,options.extraHeaders),body:JSON.stringify(requestBody(id,method,params)),credentials:'omit',cache:'no-store',redirect:'manual',signal:options.signal});if(response?.status===401){const error=new Error('MCP authorization is required before this operation can run.');error.code='MCP_AUTH_REQUIRED';throw error;}if(!response?.ok)throw new Error(`MCP ${method} failed with HTTP ${response?.status??'unknown'}.`);const payload=await readJsonRpc(response,id,maxResponseBytes);if(payload?.jsonrpc!=='2.0'||payload?.id!==id)throw new Error(`MCP ${method} returned an invalid JSON-RPC response.`);if(payload.error){const error=new Error(`MCP ${method} returned JSON-RPC error ${payload.error.code}: ${payload.error.message??'unknown error'}`);error.code=payload.error.code;throw error;}return payload.result;}

export function compileMcpToolInventory(tools,{maxTools=100}={}){const accepted=[],rejected=[],names=new Set();for(const raw of Array.isArray(tools)?tools:[]){if(accepted.length>=maxTools){rejected.push({name:raw?.name??null,reason:'tool limit exceeded'});continue;}try{if(!TOOL_NAME.test(String(raw?.name??'')))throw new TypeError('invalid MCP tool name');if(names.has(raw.name))throw new TypeError('duplicate MCP tool name');const inputSchema=raw.inputSchema??{type:'object'};const error=schemaError(inputSchema);if(error)throw new TypeError(error);const headerMappings=collectHeaderMappings(inputSchema);names.add(raw.name);accepted.push({name:raw.name,title:typeof raw.title==='string'?raw.title:null,description:typeof raw.description==='string'?raw.description:'',inputSchema,outputSchema:raw.outputSchema&&typeof raw.outputSchema==='object'?raw.outputSchema:null,annotations:raw.annotations&&typeof raw.annotations==='object'?raw.annotations:null,headerMappings,source:'mcp-2026-07-28',execution:{mode:'preview-bound',credentials:'omit',explicitApproval:true,automaticRetries:false}});}catch(error){rejected.push({name:typeof raw?.name==='string'?raw.name:null,reason:String(error?.message??error)});}}return{tools:accepted,rejected};}

export async function listModernMcpTools(endpoint,options={}){const maxPages=boundedInt(options.maxPages,8,1,16),maxTools=boundedInt(options.maxTools,100,1,500);let cursor=null,page=0,rawTools=[],cache=[];do{if(page>=maxPages)throw new Error('MCP tools/list pagination exceeded the configured page limit.');const params=cursor?{cursor}:{};const result=await post(endpoint,'tools/list',params,{...options,id:`kata-tools-list-${page+1}`});if(result?.resultType!=='complete'||!Array.isArray(result.tools))throw new Error('MCP tools/list returned an invalid complete result.');rawTools.push(...result.tools);if(rawTools.length>maxTools)throw new Error('MCP tools/list exceeded the configured tool limit.');cache.push({ttlMs:Number.isFinite(result.ttlMs)?result.ttlMs:null,cacheScope:typeof result.cacheScope==='string'?result.cacheScope:null});cursor=typeof result.nextCursor==='string'&&result.nextCursor?result.nextCursor:null;page+=1;}while(cursor);return{...compileMcpToolInventory(rawTools,{maxTools}),pages:page,cache};}

export function buildMcpToolCallPreview(candidate,args,endpoint,options={}){if(!candidate||typeof candidate!=='object'||!TOOL_NAME.test(String(candidate.name??'')))throw new TypeError('A compiled MCP tool candidate is required.');try{assertSchema(candidate.inputSchema,args);}catch(error){const details=Array.isArray(error?.details)&&error.details.length?`: ${error.details.join('; ')}`:'';throw new TypeError(`Invalid MCP tool arguments${details}`);}const mirrored={};for(const mapping of candidate.headerMappings??[]){const value=getPath(args,mapping.path);if(value!==undefined)mirrored[`Mcp-Param-${mapping.header}`]=headerValue(value,mapping.type,mapping.path);}const url=safeEndpoint(endpoint);const maxResponseBytes=boundedInt(options.maxResponseBytes,MAX_RESPONSE_BYTES,1,MAX_RESPONSE_BYTES);return{protocolVersion:MCP_VERSION,method:'tools/call',toolName:candidate.name,endpoint:url.href,arguments:canonicalize(args),inputSchema:canonicalize(candidate.inputSchema),outputSchema:candidate.outputSchema?canonicalize(candidate.outputSchema):null,headers:requestHeaders('tools/call',{'Mcp-Name':candidate.name,...mirrored}),credentials:'omit',redirect:'manual',automaticRetries:false,maxResponseBytes,readyToExecute:true};}

export async function fingerprintMcpToolCallPreview(preview,cryptoImpl=globalThis.crypto){if(!cryptoImpl?.subtle?.digest)throw new Error('Web Crypto SHA-256 is unavailable.');const bytes=new TextEncoder().encode(JSON.stringify(canonicalize(preview))),digest=await cryptoImpl.subtle.digest('SHA-256',bytes);return [...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,'0')).join('');}

export async function executeModernMcpToolCall(preview,previewFingerprint,options={}){if(options.approved!==true)throw new Error('Explicit approval is required before an MCP tool can execute.');if(typeof options.expectedFingerprint!=='string'||options.expectedFingerprint!==previewFingerprint)throw new Error('MCP tool preview fingerprint is stale or does not match.');const actual=await fingerprintMcpToolCallPreview(preview,options.cryptoImpl??globalThis.crypto);if(actual!==previewFingerprint)throw new Error('MCP tool preview fingerprint does not match the executable request.');if(preview?.credentials!=='omit'||preview?.redirect!=='manual'||preview?.automaticRetries!==false)throw new Error('MCP execution transport policy was altered.');const result=await post(preview.endpoint,'tools/call',{name:preview.toolName,arguments:preview.arguments},{fetchImpl:options.fetchImpl,signal:options.signal,maxResponseBytes:preview.maxResponseBytes,id:'kata-mcp-call',extraHeaders:Object.fromEntries(Object.entries(preview.headers??{}).filter(([name])=>name.toLowerCase().startsWith('mcp-param-')||name.toLowerCase()==='mcp-name'))});let outputValidation='not-declared';if(preview.outputSchema&&result?.resultType==='complete'&&Object.prototype.hasOwnProperty.call(result,'structuredContent')){try{assertSchema(preview.outputSchema,result.structuredContent);outputValidation='validated-supported-subset';}catch(error){const details=Array.isArray(error?.details)?error.details:[];throw new Error(`MCP structured tool output did not satisfy the declared output schema${details.length?`: ${details.join('; ')}`:''}.`);}}const receipt={previewFingerprint,toolName:preview.toolName,resultType:result?.resultType??null,isError:Boolean(result?.isError),outputValidation,automaticRetry:false};return{ok:result?.resultType==='complete'&&!result?.isError,receipt,result};}
