import {assertSchema} from '../lib/shared/schema.js';

const MCP_VERSION='2026-07-28';
const TASKS_EXTENSION='io.modelcontextprotocol/tasks';
const TOOL_NAME=/^[A-Za-z0-9_.-]{1,128}$/;
const TCHAR=/^[!#$%&'*+\-.^_`|~0-9A-Za-z]+$/;
const EXECUTABLE_SCHEMA_KEYS=new Set(['$schema','type','enum','properties','required','additionalProperties','items','minItems','maxItems','minLength','maxLength','pattern','minimum','maximum','title','description','default','examples','example','format','deprecated','readOnly','writeOnly','x-mcp-header']);
const TASK_STATUSES=new Set(['working','input_required','completed','cancelled','failed']);
const MAX_RESPONSE_BYTES=1024*1024;
const DEFAULT_TIMEOUT_MS=15000;
const MAX_TIMEOUT_MS=15000;
const MAX_MRTR_ROUNDS=10;
const MAX_INPUT_REQUESTS=16;
const MAX_REQUEST_STATE_BYTES=64*1024;
const MAX_TASK_ID_BYTES=4096;

function safeEndpoint(raw){try{const url=new URL(String(raw));if(!['http:','https:'].includes(url.protocol)||url.username||url.password)throw new Error();url.hash='';return url;}catch{throw new TypeError('A safe HTTP(S) MCP endpoint is required.');}}
function boundedInt(value,fallback,min,max){const n=Number(value);return Number.isInteger(n)?Math.max(min,Math.min(max,n)):fallback;}
function canonicalize(value){if(value===null||typeof value==='string'||typeof value==='boolean')return value;if(typeof value==='number'){if(!Number.isFinite(value))throw new TypeError('MCP preview contains a non-finite number.');return value;}if(Array.isArray(value))return value.map(canonicalize);if(value&&typeof value==='object'){const out={};for(const key of Object.keys(value).sort())out[key]=canonicalize(value[key]);return out;}throw new TypeError('MCP preview contains a non-JSON value.');}
function schemaError(schema,path='$'){if(!schema||typeof schema!=='object'||Array.isArray(schema))return `schema is not an executable JSON Schema object at ${path}`;for(const key of Object.keys(schema))if(!EXECUTABLE_SCHEMA_KEYS.has(key))return `unsupported executable JSON Schema keyword ${key} at ${path}`;if(Array.isArray(schema.type))return `union types are not executable at ${path}`;if(schema.additionalProperties!==undefined&&typeof schema.additionalProperties!=='boolean')return `schema-valued additionalProperties is not executable at ${path}`;if(schema.properties!==undefined){if(!schema.properties||typeof schema.properties!=='object'||Array.isArray(schema.properties))return `invalid properties at ${path}`;for(const [name,child] of Object.entries(schema.properties)){const error=schemaError(child,`${path}.properties.${name}`);if(error)return error;}}if(schema.items!==undefined){const error=schemaError(schema.items,`${path}.items`);if(error)return error;}return null;}
function collectHeaderMappings(schema,path=[],seen=new Map(),out=[]){for(const [name,child] of Object.entries(schema?.properties??{})){const next=[...path,name],header=child?.['x-mcp-header'];if(header!==undefined){if(typeof header!=='string'||!header||!TCHAR.test(header))throw new TypeError(`Invalid x-mcp-header on ${next.join('.')}`);if(!['string','integer','boolean'].includes(child?.type))throw new TypeError(`x-mcp-header requires string, integer, or boolean at ${next.join('.')}`);const lower=header.toLowerCase();if(seen.has(lower))throw new TypeError(`Duplicate x-mcp-header value: ${header}`);seen.set(lower,true);out.push({path:next,header,type:child.type});}if(child?.type==='object')collectHeaderMappings(child,next,seen,out);}return out;}
function getPath(value,path){let current=value;for(const part of path){if(current===null||typeof current!=='object'||!(part in current))return undefined;current=current[part];}return current;}
function base64Utf8(value){const bytes=new TextEncoder().encode(value);let binary='';for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,i+0x8000));if(typeof globalThis.btoa!=='function')throw new Error('Base64 encoder is unavailable.');return globalThis.btoa(binary);}
function encodeHeaderString(value){const boundaryWhitespace=/^[\t ]|[\t ]$/.test(value);let plain=!boundaryWhitespace;for(let i=0;i<value.length&&plain;i++){const code=value.charCodeAt(i);if(code===0x09)continue;if(code<0x20||code>0x7e)plain=false;}return plain?value:`=?base64?${base64Utf8(value)}?=`;}
function headerValue(value,type,path){let text;if(type==='integer'){if(!Number.isSafeInteger(value))throw new TypeError(`MCP mirrored integer is outside the safe range at ${path.join('.')}`);text=String(value);}else if(type==='boolean'){if(typeof value!=='boolean')throw new TypeError(`MCP mirrored boolean is invalid at ${path.join('.')}`);text=value?'true':'false';}else{if(typeof value!=='string')throw new TypeError(`MCP mirrored string is invalid at ${path.join('.')}`);text=value;}return encodeHeaderString(text);}
function utf8Bytes(value){return new TextEncoder().encode(String(value??'')).length;}
function safeTaskId(raw){if(typeof raw!=='string'||!raw||utf8Bytes(raw)>MAX_TASK_ID_BYTES)throw new TypeError('A bounded MCP task id is required.');for(let i=0;i<raw.length;i++){const code=raw.charCodeAt(i);if(code<0x21||code>0x7e)throw new TypeError('MCP task id must be a header-safe opaque ASCII value.');}return raw;}
function meta(tasksExtension=false){const capabilities=tasksExtension?{extensions:{[TASKS_EXTENSION]:{}}}:{};return{'io.modelcontextprotocol/protocolVersion':MCP_VERSION,'io.modelcontextprotocol/clientCapabilities':capabilities,'io.modelcontextprotocol/clientInfo':{name:'kata-interop-adapter',version:'3.0.0'}};}
function requestBody(id,method,params={},options={}){return{jsonrpc:'2.0',id,method,params:{...params,_meta:meta(options.tasksExtension===true)}};}
function requestHeaders(method,extra={}){return{'Content-Type':'application/json','Accept':'application/json, text/event-stream','MCP-Protocol-Version':MCP_VERSION,'Mcp-Method':method,...extra};}
async function boundedText(response,maxBytes){if(response?.body?.getReader){const reader=response.body.getReader(),chunks=[];let total=0;try{while(true){const {done,value}=await reader.read();if(done)break;const chunk=value instanceof Uint8Array?value:new Uint8Array(value??[]);if(total+chunk.length>maxBytes){await reader.cancel?.();throw new Error('MCP response exceeded the bounded response limit.');}chunks.push(chunk);total+=chunk.length;}}finally{try{reader.releaseLock?.();}catch{}}const merged=new Uint8Array(total);let offset=0;for(const chunk of chunks){merged.set(chunk,offset);offset+=chunk.length;}return new TextDecoder().decode(merged);}if(typeof response?.text==='function'){const text=await response.text();if(new TextEncoder().encode(text).length>maxBytes)throw new Error('MCP response exceeded the bounded response limit.');return text;}throw new Error('MCP response body is unavailable.');}
async function readSseJsonRpc(response,id,maxBytes){const text=await boundedText(response,maxBytes);let data=[];for(const line of text.split(/\r?\n/)){if(line.startsWith(':'))continue;if(line.startsWith('data:'))data.push(line.slice(5).trimStart());else if(line===''){if(data.length){const raw=data.join('\n');data=[];try{const value=JSON.parse(raw);if(value?.id===id)return value;}catch{}}}}if(data.length){try{const value=JSON.parse(data.join('\n'));if(value?.id===id)return value;}catch{}}throw new Error('MCP SSE response ended without the final JSON-RPC response.');}
async function readJsonRpc(response,id,maxBytes=MAX_RESPONSE_BYTES){const type=String(response?.headers?.get?.('content-type')??'').toLowerCase();if(type.includes('text/event-stream'))return readSseJsonRpc(response,id,maxBytes);if(response?.body?.getReader||typeof response?.text==='function')return JSON.parse(await boundedText(response,maxBytes));if(typeof response?.json==='function')return response.json();throw new Error('MCP JSON-RPC response body is unavailable.');}
function timeoutError(method){const error=new Error(`MCP ${method} timed out.`);error.code='MCP_TIMEOUT';return error;}
async function post(endpoint,method,params,options={}){
  const fetchImpl=options.fetchImpl??globalThis.fetch;if(typeof fetchImpl!=='function')throw new Error('fetch is unavailable.');
  const id=options.id??`kata-${method.replace('/','-')}`;
  const maxResponseBytes=boundedInt(options.maxResponseBytes,MAX_RESPONSE_BYTES,1,MAX_RESPONSE_BYTES);
  const timeoutMs=boundedInt(options.timeoutMs,DEFAULT_TIMEOUT_MS,250,MAX_TIMEOUT_MS);
  const AbortControllerImpl=options.AbortControllerImpl??globalThis.AbortController;if(typeof AbortControllerImpl!=='function')throw new Error('AbortController is unavailable.');
  const setTimer=options.setTimeoutImpl??globalThis.setTimeout,clearTimer=options.clearTimeoutImpl??globalThis.clearTimeout;
  const controller=new AbortControllerImpl();let timedOut=false;
  const externalSignal=options.signal;
  const onExternalAbort=()=>{try{controller.abort(externalSignal?.reason);}catch{controller.abort();}};
  if(externalSignal?.aborted)onExternalAbort();else externalSignal?.addEventListener?.('abort',onExternalAbort,{once:true});
  const timer=setTimer(()=>{timedOut=true;try{controller.abort(new Error('KATA_MCP_TIMEOUT'));}catch{controller.abort();}},timeoutMs);
  try{
    let response;
    try{response=await fetchImpl(safeEndpoint(endpoint).href,{method:'POST',headers:requestHeaders(method,options.extraHeaders),body:JSON.stringify(requestBody(id,method,params,{tasksExtension:options.tasksExtension===true})),credentials:'omit',cache:'no-store',redirect:'manual',signal:controller.signal});}
    catch(error){if(timedOut)throw timeoutError(method);throw error;}
    if(response?.status===401){const error=new Error('MCP authorization is required before this operation can run.');error.code='MCP_AUTH_REQUIRED';throw error;}
    if(!response?.ok)throw new Error(`MCP ${method} failed with HTTP ${response?.status??'unknown'}.`);
    let payload;
    try{payload=await readJsonRpc(response,id,maxResponseBytes);}catch(error){if(timedOut)throw timeoutError(method);throw error;}
    if(payload?.jsonrpc!=='2.0'||payload?.id!==id)throw new Error(`MCP ${method} returned an invalid JSON-RPC response.`);
    if(payload.error){const error=new Error(`MCP ${method} returned JSON-RPC error ${payload.error.code}: ${payload.error.message??'unknown error'}`);error.code=payload.error.code;throw error;}
    return payload.result;
  }finally{
    clearTimer(timer);
    externalSignal?.removeEventListener?.('abort',onExternalAbort);
  }
}

function normalizeInputRequests(inputRequests,{allowEmpty=false}={}){if(inputRequests===undefined||inputRequests===null){if(allowEmpty)return{inputRequests:null,supported:true,unsupported:[]};throw new Error('MCP input requests are required.');}if(!inputRequests||typeof inputRequests!=='object'||Array.isArray(inputRequests))throw new Error('MCP input requests are invalid.');const entries=Object.entries(inputRequests);if((!allowEmpty&&entries.length<1)||entries.length>MAX_INPUT_REQUESTS)throw new Error('MCP input requests exceed the bounded request count.');const unsupported=[];for(const [key,request] of entries){if(!key||typeof key!=='string')throw new Error('MCP input requests contain an invalid request key.');const method=String(request?.method??'');if(method!=='elicitation/create')unsupported.push({key,method:method||null});}return{inputRequests:canonicalize(inputRequests),supported:unsupported.length===0,unsupported};}
function normalizeInputRequired(result,round){if(result?.resultType!=='input_required')return null;if(!Number.isInteger(round)||round<1||round>MAX_MRTR_ROUNDS)throw new TypeError('Invalid MCP multi-round-trip round.');const normalized=normalizeInputRequests(result.inputRequests);const requestState=result.requestState;if(requestState!==undefined&&typeof requestState!=='string')throw new Error('MCP input_required requestState must be an opaque string when present.');if(typeof requestState==='string'&&utf8Bytes(requestState)>MAX_REQUEST_STATE_BYTES)throw new Error('MCP input_required requestState exceeds the bounded size limit.');return{round,...normalized,requestState:requestState??null};}
function validateElicitationResponse(key,request,response){if(request?.method!=='elicitation/create')throw new TypeError(`Unsupported MCP input request method for ${key}: ${request?.method??'unknown'}`);const params=request.params;if(!params||typeof params!=='object'||Array.isArray(params)||!params.requestedSchema)throw new TypeError(`MCP elicitation request is missing requestedSchema for ${key}`);if(params.url!==undefined||params.mode==='url')throw new TypeError(`Unsupported MCP elicitation mode for ${key}: URL-mode elicitation requires an out-of-band user flow`);const schemaIssue=schemaError(params.requestedSchema,`inputRequests.${key}.params.requestedSchema`);if(schemaIssue)throw new TypeError(`Unsupported MCP elicitation schema for ${key}: ${schemaIssue}`);const action=response?.action;if(!['accept','decline','cancel'].includes(action))throw new TypeError(`Invalid MCP elicitation response action for ${key}`);if(action==='accept'){if(!Object.prototype.hasOwnProperty.call(response,'content'))throw new TypeError(`Invalid MCP elicitation response for ${key}: accepted response requires content`);try{assertSchema(params.requestedSchema,response.content);}catch(error){const details=Array.isArray(error?.details)&&error.details.length?`: ${error.details.join('; ')}`:'';throw new TypeError(`Invalid MCP elicitation response for ${key}${details}`);}return{action:'accept',content:canonicalize(response.content)};}if(Object.prototype.hasOwnProperty.call(response??{},'content'))throw new TypeError(`Invalid MCP elicitation response for ${key}: ${action} must not carry content`);return{action};}
function validateOutput(outputSchema,outputSchemaValidation,result){let validation=outputSchemaValidation??'not-declared';if(outputSchema&&result?.resultType==='complete'&&Object.prototype.hasOwnProperty.call(result,'structuredContent')){if(validation==='supported-subset'){try{assertSchema(outputSchema,result.structuredContent);validation='validated-supported-subset';}catch(error){const details=Array.isArray(error?.details)?error.details:[];throw new Error(`MCP structured tool output did not satisfy the declared output schema${details.length?`: ${details.join('; ')}`:''}.`);}}else validation='not-validated-unsupported-schema';}else if(outputSchema&&result?.resultType==='complete')validation='missing-structured-content';return validation;}
function normalizeTaskState(raw,context={}){if(!raw||typeof raw!=='object'||Array.isArray(raw))throw new Error('MCP task result is invalid.');const taskId=safeTaskId(raw.taskId);const status=String(raw.status??'');if(!TASK_STATUSES.has(status))throw new Error(`MCP task returned invalid status: ${status||'missing'}.`);const ttlMs=Number.isFinite(raw.ttlMs)&&raw.ttlMs>=0?raw.ttlMs:null;const pollIntervalMs=Number.isFinite(raw.pollIntervalMs)&&raw.pollIntervalMs>=0?raw.pollIntervalMs:null;const requests=status==='input_required'?normalizeInputRequests(raw.inputRequests):{inputRequests:null,supported:true,unsupported:[]};return{taskId,status,createdAt:typeof raw.createdAt==='string'?raw.createdAt:null,lastUpdatedAt:typeof raw.lastUpdatedAt==='string'?raw.lastUpdatedAt:null,ttlMs,pollIntervalMs,...requests,result:raw.result??null,endpoint:context.endpoint?safeEndpoint(context.endpoint).href:null,toolName:typeof context.toolName==='string'?context.toolName:null,outputSchema:context.outputSchema?canonicalize(context.outputSchema):null,outputSchemaValidation:context.outputSchemaValidation??'not-declared',previewFingerprint:typeof context.previewFingerprint==='string'?context.previewFingerprint:null,automaticPolling:false};}
function normalizeCreatedTask(result,preview,previewFingerprint){if(result?.resultType!=='task')return null;return normalizeTaskState(result,{endpoint:preview.endpoint,toolName:preview.toolName,outputSchema:preview.outputSchema,outputSchemaValidation:preview.outputSchemaValidation,previewFingerprint});}
function finalResult(preview,previewFingerprint,result,round){const outputValidation=validateOutput(preview.outputSchema,preview.outputSchemaValidation,result);const continuation=normalizeInputRequired(result,round);const task=normalizeCreatedTask(result,preview,previewFingerprint);const receipt={previewFingerprint,toolName:preview.toolName,resultType:result?.resultType??null,isError:Boolean(result?.isError),outputValidation,inputRequired:Boolean(continuation),taskCreated:Boolean(task),automaticRetry:false,round};return{ok:result?.resultType==='complete'&&!result?.isError,receipt,result,continuation,task};}

export function compileMcpToolInventory(tools,{maxTools=100}={}){const accepted=[],rejected=[],names=new Set();for(const raw of Array.isArray(tools)?tools:[]){if(accepted.length>=maxTools){rejected.push({name:raw?.name??null,reason:'tool limit exceeded'});continue;}try{if(!TOOL_NAME.test(String(raw?.name??'')))throw new TypeError('invalid MCP tool name');if(names.has(raw.name))throw new TypeError('duplicate MCP tool name');const taskSupport=raw?.execution?.taskSupport??'forbidden';if(!['forbidden','optional','required'].includes(taskSupport))throw new TypeError(`invalid MCP taskSupport: ${taskSupport}`);const inputSchema=raw.inputSchema??{type:'object'};const inputError=schemaError(inputSchema);if(inputError)throw new TypeError(`inputSchema: ${inputError}`);const headerMappings=collectHeaderMappings(inputSchema);const outputSchema=raw.outputSchema&&typeof raw.outputSchema==='object'?raw.outputSchema:null;const outputSchemaValidation=outputSchema?(schemaError(outputSchema)?'unsupported-schema':'supported-subset'):'not-declared';names.add(raw.name);accepted.push({name:raw.name,title:typeof raw.title==='string'?raw.title:null,description:typeof raw.description==='string'?raw.description:'',inputSchema,outputSchema,outputSchemaValidation,annotations:raw.annotations&&typeof raw.annotations==='object'?raw.annotations:null,taskSupport,headerMappings,source:'mcp-2026-07-28',execution:{mode:'preview-bound',credentials:'omit',explicitApproval:true,automaticRetries:false,multiRoundTrip:'explicit-elicitation-only',tasks:taskSupport==='forbidden'?'not-advertised':'explicit-manual-lifecycle'}});}catch(error){rejected.push({name:typeof raw?.name==='string'?raw.name:null,reason:String(error?.message??error)});}}return{tools:accepted,rejected};}
export async function listModernMcpTools(endpoint,options={}){const maxPages=boundedInt(options.maxPages,8,1,16),maxTools=boundedInt(options.maxTools,100,1,500);let cursor=null,page=0,rawTools=[],cache=[];do{if(page>=maxPages)throw new Error('MCP tools/list pagination exceeded the configured page limit.');const params=cursor?{cursor}:{};const result=await post(endpoint,'tools/list',params,{...options,id:`kata-tools-list-${page+1}`});if(result?.resultType!=='complete'||!Array.isArray(result.tools))throw new Error('MCP tools/list returned an invalid complete result.');rawTools.push(...result.tools);if(rawTools.length>maxTools)throw new Error('MCP tools/list exceeded the configured tool limit.');cache.push({ttlMs:Number.isFinite(result.ttlMs)?result.ttlMs:null,cacheScope:typeof result.cacheScope==='string'?result.cacheScope:null});cursor=typeof result.nextCursor==='string'&&result.nextCursor?result.nextCursor:null;page+=1;}while(cursor);return{...compileMcpToolInventory(rawTools,{maxTools}),pages:page,cache};}
export function buildMcpToolCallPreview(candidate,args,endpoint,options={}){if(!candidate||typeof candidate!=='object'||!TOOL_NAME.test(String(candidate.name??'')))throw new TypeError('A compiled MCP tool candidate is required.');try{assertSchema(candidate.inputSchema,args);}catch(error){const details=Array.isArray(error?.details)&&error.details.length?`: ${error.details.join('; ')}`:'';throw new TypeError(`Invalid MCP tool arguments${details}`);}const mirrored={};for(const mapping of candidate.headerMappings??[]){const value=getPath(args,mapping.path);if(value!==undefined)mirrored[`Mcp-Param-${mapping.header}`]=headerValue(value,mapping.type,mapping.path);}const url=safeEndpoint(endpoint);const maxResponseBytes=boundedInt(options.maxResponseBytes,MAX_RESPONSE_BYTES,1,MAX_RESPONSE_BYTES),timeoutMs=boundedInt(options.timeoutMs,DEFAULT_TIMEOUT_MS,250,MAX_TIMEOUT_MS);const taskSupport=candidate.taskSupport??'forbidden';return{protocolVersion:MCP_VERSION,method:'tools/call',toolName:candidate.name,endpoint:url.href,arguments:canonicalize(args),inputSchema:canonicalize(candidate.inputSchema),outputSchema:candidate.outputSchema?canonicalize(candidate.outputSchema):null,outputSchemaValidation:candidate.outputSchemaValidation??'not-declared',taskSupport,tasksExtension:taskSupport!=='forbidden',headers:requestHeaders('tools/call',{'Mcp-Name':candidate.name,...mirrored}),credentials:'omit',redirect:'manual',automaticRetries:false,maxResponseBytes,timeoutMs,round:1,readyToExecute:true};}
export function buildMcpInputRequiredResumePreview(previousPreview,inputRequiredResult,inputResponses,options={}){if(!previousPreview||previousPreview.method!=='tools/call'||!TOOL_NAME.test(String(previousPreview.toolName??'')))throw new TypeError('A valid MCP tools/call preview is required to resume input_required.');const currentRound=boundedInt(options.round,Number.isInteger(previousPreview.round)?previousPreview.round:1,1,MAX_MRTR_ROUNDS);if(currentRound>=MAX_MRTR_ROUNDS)throw new Error(`MCP multi-round-trip round limit (${MAX_MRTR_ROUNDS}) exceeded.`);const continuation=normalizeInputRequired(inputRequiredResult,currentRound);if(!continuation)throw new TypeError('An MCP input_required result is required to build a resume preview.');if(!continuation.supported){const first=continuation.unsupported[0];throw new TypeError(`Unsupported MCP input request method for ${first.key}: ${first.method??'unknown'}`);}if(!inputResponses||typeof inputResponses!=='object'||Array.isArray(inputResponses))throw new TypeError('MCP inputResponses must be an object keyed by the current inputRequests.');const requestKeys=Object.keys(continuation.inputRequests),responseKeys=Object.keys(inputResponses);if(responseKeys.length!==requestKeys.length||responseKeys.some(key=>!Object.prototype.hasOwnProperty.call(continuation.inputRequests,key)))throw new TypeError('MCP inputResponses must answer exactly the current inputRequests and must not accumulate prior rounds.');const normalized={};for(const key of requestKeys)normalized[key]=validateElicitationResponse(key,continuation.inputRequests[key],inputResponses[key]);return{...canonicalize(previousPreview),round:currentRound+1,inputResponses:canonicalize(normalized),requestState:continuation.requestState,readyToExecute:true};}
export async function fingerprintMcpToolCallPreview(preview,cryptoImpl=globalThis.crypto){if(!cryptoImpl?.subtle?.digest)throw new Error('Web Crypto SHA-256 is unavailable.');const bytes=new TextEncoder().encode(JSON.stringify(canonicalize(preview))),digest=await cryptoImpl.subtle.digest('SHA-256',bytes);return [...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,'0')).join('');}
function assertExecutablePreview(preview){if(preview?.credentials!=='omit'||preview?.redirect!=='manual'||preview?.automaticRetries!==false)throw new Error('MCP execution transport policy was altered.');if(preview?.taskSupport==='required'&&preview?.tasksExtension!==true)throw new Error('MCP Tasks-extension-required tools must explicitly advertise the Tasks client capability.');}
function executionHeaders(preview){return Object.fromEntries(Object.entries(preview.headers??{}).filter(([name])=>name.toLowerCase().startsWith('mcp-param-')||name.toLowerCase()==='mcp-name'));}
export async function executeModernMcpToolCall(preview,previewFingerprint,options={}){if(options.approved!==true)throw new Error('Explicit approval is required before an MCP tool can execute.');if(typeof options.expectedFingerprint!=='string'||options.expectedFingerprint!==previewFingerprint)throw new Error('MCP tool preview fingerprint is stale or does not match.');const actual=await fingerprintMcpToolCallPreview(preview,options.cryptoImpl??globalThis.crypto);if(actual!==previewFingerprint)throw new Error('MCP tool preview fingerprint does not match the executable request.');assertExecutablePreview(preview);const result=await post(preview.endpoint,'tools/call',{name:preview.toolName,arguments:preview.arguments},{fetchImpl:options.fetchImpl,signal:options.signal,maxResponseBytes:preview.maxResponseBytes,timeoutMs:preview.timeoutMs,id:'kata-mcp-call',extraHeaders:executionHeaders(preview),tasksExtension:preview.tasksExtension===true});return finalResult(preview,previewFingerprint,result,1);}
export async function executeModernMcpToolResume(preview,previewFingerprint,options={}){if(options.approved!==true)throw new Error('Explicit approval is required before an MCP input_required round can resume.');if(typeof options.expectedFingerprint!=='string'||options.expectedFingerprint!==previewFingerprint)throw new Error('MCP resume preview fingerprint is stale or does not match.');const actual=await fingerprintMcpToolCallPreview(preview,options.cryptoImpl??globalThis.crypto);if(actual!==previewFingerprint)throw new Error('MCP resume preview fingerprint does not match the executable request.');assertExecutablePreview(preview);const round=boundedInt(preview?.round,0,2,MAX_MRTR_ROUNDS);if(round<2)throw new Error('MCP resume preview is missing a valid multi-round-trip round.');if(!preview.inputResponses||typeof preview.inputResponses!=='object'||Array.isArray(preview.inputResponses))throw new Error('MCP resume preview is missing inputResponses.');const params={name:preview.toolName,arguments:preview.arguments,inputResponses:preview.inputResponses};if(preview.requestState!==null&&preview.requestState!==undefined)params.requestState=preview.requestState;const result=await post(preview.endpoint,'tools/call',params,{fetchImpl:options.fetchImpl,signal:options.signal,maxResponseBytes:preview.maxResponseBytes,timeoutMs:preview.timeoutMs,id:`kata-mcp-call-r${round}`,extraHeaders:executionHeaders(preview),tasksExtension:preview.tasksExtension===true});return finalResult(preview,previewFingerprint,result,round);}

function assertTaskContext(task){if(!task||typeof task!=='object'||Array.isArray(task))throw new TypeError('A valid MCP task context is required.');const taskId=safeTaskId(task.taskId);const endpoint=safeEndpoint(task.endpoint).href;return{...task,taskId,endpoint};}
function taskPostOptions(task,options,id){return{fetchImpl:options.fetchImpl,signal:options.signal,maxResponseBytes:boundedInt(options.maxResponseBytes,MAX_RESPONSE_BYTES,1,MAX_RESPONSE_BYTES),timeoutMs:boundedInt(options.timeoutMs,DEFAULT_TIMEOUT_MS,250,MAX_TIMEOUT_MS),id,extraHeaders:{'Mcp-Name':task.taskId},tasksExtension:true};}
export async function getModernMcpTask(task,options={}){const context=assertTaskContext(task);const result=await post(context.endpoint,'tasks/get',{taskId:context.taskId},taskPostOptions(context,options,'kata-task-get'));if(result?.resultType!=='complete')throw new Error('MCP tasks/get returned an invalid complete result.');const normalized=normalizeTaskState(result,context);let outputValidation=context.outputSchemaValidation??'not-declared';if(normalized.status==='completed'&&normalized.result)outputValidation=validateOutput(context.outputSchema,context.outputSchemaValidation,normalized.result);return{...normalized,outputValidation,automaticPolling:false};}
function taskPreviewBase(task,method,options={}){const context=assertTaskContext(task);return{protocolVersion:MCP_VERSION,method,taskId:context.taskId,endpoint:context.endpoint,toolName:typeof context.toolName==='string'?context.toolName:null,originPreviewFingerprint:typeof context.previewFingerprint==='string'?context.previewFingerprint:null,tasksExtension:true,headers:requestHeaders(method,{'Mcp-Name':context.taskId}),credentials:'omit',redirect:'manual',automaticRetries:false,maxResponseBytes:boundedInt(options.maxResponseBytes,MAX_RESPONSE_BYTES,1,MAX_RESPONSE_BYTES),timeoutMs:boundedInt(options.timeoutMs,DEFAULT_TIMEOUT_MS,250,MAX_TIMEOUT_MS),readyToExecute:true};}
export function buildMcpTaskUpdatePreview(task,inputResponses,options={}){const context=assertTaskContext(task);if(context.status!=='input_required')throw new TypeError('MCP task must be input_required before tasks/update can be previewed.');const normalizedRequests=normalizeInputRequests(context.inputRequests);if(!normalizedRequests.supported){const first=normalizedRequests.unsupported[0];throw new TypeError(`Unsupported MCP task input request method for ${first.key}: ${first.method??'unknown'}`);}if(!inputResponses||typeof inputResponses!=='object'||Array.isArray(inputResponses)||Object.keys(inputResponses).length<1)throw new TypeError('MCP task inputResponses must answer at least one current task inputRequest.');const normalized={};for(const [key,response] of Object.entries(inputResponses)){if(!Object.prototype.hasOwnProperty.call(normalizedRequests.inputRequests,key))throw new TypeError('MCP task inputResponses must answer only current task inputRequests.');normalized[key]=validateElicitationResponse(key,normalizedRequests.inputRequests[key],response);}return{...taskPreviewBase(context,'tasks/update',options),inputResponses:canonicalize(normalized)};}
export async function executeModernMcpTaskUpdate(preview,previewFingerprint,options={}){if(options.approved!==true)throw new Error('Explicit approval is required before MCP task input can be submitted.');if(typeof options.expectedFingerprint!=='string'||options.expectedFingerprint!==previewFingerprint)throw new Error('MCP task update preview fingerprint is stale or does not match.');const actual=await fingerprintMcpToolCallPreview(preview,options.cryptoImpl??globalThis.crypto);if(actual!==previewFingerprint)throw new Error('MCP task update preview fingerprint does not match the executable request.');assertExecutablePreview(preview);if(preview.method!=='tasks/update'||!preview.inputResponses)throw new Error('Invalid MCP tasks/update preview.');const result=await post(preview.endpoint,'tasks/update',{taskId:preview.taskId,inputResponses:preview.inputResponses},{fetchImpl:options.fetchImpl,signal:options.signal,maxResponseBytes:preview.maxResponseBytes,timeoutMs:preview.timeoutMs,id:'kata-task-update',extraHeaders:{'Mcp-Name':safeTaskId(preview.taskId)},tasksExtension:true});return{ok:true,taskId:preview.taskId,updateAccepted:true,automaticPolling:false,result};}
export function buildMcpTaskCancelPreview(task,options={}){return taskPreviewBase(task,'tasks/cancel',options);}
export async function executeModernMcpTaskCancel(preview,previewFingerprint,options={}){if(options.approved!==true)throw new Error('Explicit approval is required before an MCP task can be cancelled.');if(typeof options.expectedFingerprint!=='string'||options.expectedFingerprint!==previewFingerprint)throw new Error('MCP task cancel preview fingerprint is stale or does not match.');const actual=await fingerprintMcpToolCallPreview(preview,options.cryptoImpl??globalThis.crypto);if(actual!==previewFingerprint)throw new Error('MCP task cancel preview fingerprint does not match the executable request.');assertExecutablePreview(preview);if(preview.method!=='tasks/cancel')throw new Error('Invalid MCP tasks/cancel preview.');const taskId=safeTaskId(preview.taskId);const result=await post(preview.endpoint,'tasks/cancel',{taskId},{fetchImpl:options.fetchImpl,signal:options.signal,maxResponseBytes:preview.maxResponseBytes,timeoutMs:preview.timeoutMs,id:'kata-task-cancel',extraHeaders:{'Mcp-Name':taskId},tasksExtension:true});return{ok:true,taskId,cancelRequested:true,terminalStateClaimed:false,automaticPolling:false,result};}
